### PR TITLE
exclude maven-antrun-plugin:run from lifecycle-mapping

### PR DESCRIPTION
**Pull request by LorenzoBettini**
Otherwise there's an error on the POM and in any case there's no
connector for maven-antrun-plugin

Signed-off-by: Lorenzo Bettini <lorenzo.bettini@gmail.com>

### CODE REVIEW

**Comment by LorenzoBettini** [comment]
@laeubi This is just to avoid having an error on the POM in the IDE

**Comment by mickaelistria** [comment]
I'd rather have such workarounds prevented in Tycho. Instead it would be great to make the maven-antrun-plugin add the necessary metadata and use the right API for m2e to not complain about it.

**Comment by LorenzoBettini** [comment]
@mickaelistria as I said, I never found any connector for the maven-antrun-plugin...

**Comment by mickaelistria** [comment]
It's putting lipstick on a pig ;)

**Comment by LorenzoBettini** [comment]
:D anyway, please feel free to close it if you think it's not worthwhile (but I guess the error marker should then be documented in the contribution guide)

**Comment by laeubi** [comment]
I always found the m2e way to suppress things like this in the pom rather "disruptive".. @LorenzoBettini have you checked if we can ignore this in the **Workspace** instead using a setup file?

>  I never found any connector for the maven-antrun-plugin...

I'm not sure how m2e handles this in details but if I understand Mickael correctly you could place some data inside the antrun-plugin itself?!

**Comment by LorenzoBettini** [comment]
> I always found the m2e way to suppress things like this in the pom rather "disruptive".. @LorenzoBettini have you checked if we can ignore this in the **Workspace** instead using a setup file?
> 

Probably this can be excluded at the workspace level, with some kind of preference that is stored in the setup file. For sure it can be ignored at the workspace level (because m2e provides such a quickfix), but I don't know if that can be stored somehow in the setup

> > I never found any connector for the maven-antrun-plugin...
> 
> I'm not sure how m2e handles this in details but if I understand Mickael correctly you could place some data inside the antrun-plugin itself?!

not that I'm aware of... or maybe I do not understand what Mickael suggests

**Comment by mickaelistria** [comment]
See https://www.eclipse.org/m2e/documentation/m2e-making-maven-plugins-compat.html . Maven plugins can be made compatible with incremental builders (such as m2e) or at least declare whether they are compatible or not so that the tools can take the best decision without bothering user with that.

**Comment by LorenzoBettini** [comment]
@mickaelistria what I've done in the past is, instead of ignoring a plugin goal, bind a goal to the build with a mapping similar to what suggested in the link you mentioned:

```xml
<lifecycleMappingMetadata>
  <pluginExecutions>
    <pluginExecution>
      <pluginExecutionFilter>
        <goals>
          <goal>some-goal</goal>
        </goals>
      </pluginExecutionFilter>
      <action>
        <execute>
          <runOnIncremental>see below</runOnIncremental>
          <runOnConfiguration>see below</runOnConfiguration>
        </execute>
      </action>
    </pluginExecution>
  </pluginExecutions>
</lifecycleMappingMetadata>
```

IIRC I bound the goal to a clean build, not incremental because that was making everything slow.

Were you suggesting something like that? It's still a m2e lifecycle mapping.

If you were suggesting something more programmatic (https://www.eclipse.org/m2e/documentation/m2e-making-maven-plugins-compat.html#buildcontext) then I wouldn't know what would be the best option.

**Comment by laeubi** [comment]
>  I wouldn't know what would be the best option.

The best option would be to convince the maven-antrun plugin add m2e metadata. I just can't tell if it should really be skipped, or instead should be executed as part of the build. As maven can do *anything* it might be good to at least execute it in the `runOnConfiguration` ...

**Comment by mickaelistria** [comment]
The best option is actually to contribute the desired change to the Maven plugin.

**Comment by LorenzoBettini** [comment]
I leave it up to you guys... since this has never been executed in Eclipse I still think it's best to exclude it... if it has to be executed by Eclipse as well I don't know how to contribute.
If you're happy with the current state, I think that at least this error marker should be documented in the contribution guide

**Comment by laeubi** [comment]
> since this has never been executed in Eclipse I still think it's best to exclude it.

I think one can start with this, this would then be required a PR/Change in the https://github.com/apache/maven-antrun-plugin @LorenzoBettini would you like to create a PR there?

**Comment by LorenzoBettini** [comment]
> > since this has never been executed in Eclipse I still think it's best to exclude it.
> 
> I think one can start with this, this would then be required a PR/Change in the https://github.com/apache/maven-antrun-plugin @LorenzoBettini would you like to create a PR there?

Sorry, I don't understand what you mean.. I said it should be excluded as I proposed in this PR you've just closed. What should I do in the maven plugin?

**Comment by laeubi** [comment]
> What should I do in the maven plugin?

The maven-plugin should include the [META-INF/m2e/lifecycle-mapping-metadata.xml ](https://www.eclipse.org/m2e/documentation/m2e-making-maven-plugins-compat.html#mapping) then the warning/error won'T apear anymor (not only for tycho)

It could be something like 
```
<lifecycleMappingMetadata>
  <pluginExecutions>
    <pluginExecution>
      <pluginExecutionFilter>
        <goals>
          <goal>run</goal>
        </goals>
      </pluginExecutionFilter>
      <action>
        <ignore/>
      </action>
    </pluginExecution>
  </pluginExecutions>
</lifecycleMappingMetadata>
```

**Comment by LorenzoBettini** [comment]
@laeubi if you think that's the way to go, please open the PR yourself.
I still think that the solution I proposed in this closed PR is the way to go...

**Comment by laeubi** [comment]
I'll take a look I'm just not sure if it would be a good idea to actually execute the ant-run plugin as it obviously can do something relevant to the build...

**Comment by LorenzoBettini** [comment]
> I'll take a look I'm just not sure if it would be a good idea to actually execute the ant-run plugin as it obviously can do something relevant to the build...

to "execute" or to "exclude"?

**Pull request closed without merging**
