### PR TITLE
Create a funding.yml file

### PR DESCRIPTION
**Pull request by laeubi**
What do you think? I'm not sure if we can use the "custom" for linking to the "active member companies" or maybe eclipse-cbi can provide a custom badge?

### CODE REVIEW

**Review by akurtakov — APPROVED** [review]
I would say merge it as it is and further improvements can be done later if anyone is interested.

**Comment by laeubi** [comment]
@akurtakov what is left no is enable the sponsoring in the settings: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository#displaying-a-sponsor-button-in-your-repository

**Comment by akurtakov** [comment]
This setting is not visible for me. Please check with EF whether it's disabled by default and can be enabled. https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues should be the place to do it and add me on cc to the issue.

**Comment by laeubi** [comment]
Done, but I have no idea to cc one so here is the link: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/963

**Pull request merged**
