### PR TITLE
Use strict order and requse toolchain search from ExecutionEnvironmentUtils

### PR DESCRIPTION
**Pull request by laeubi**
FYI @akurtakov

### CODE REVIEW

**Comment by laeubi** [comment]
This will fix: https://ci.eclipse.org/equinox/job/rt.equinox.framework/job/master/112/console

**Comment by akurtakov** [comment]
Thanks, let's push and see.

**Comment by akurtakov** [comment]
Unfortunately didn't help out.

**Comment by laeubi** [comment]
I triggered a build with `-U` (update snapshots) to be sure here, the error indicates that still an old version is used.

**Comment by akurtakov** [comment]
It worked locally but I don't have Java 1.8 installed so no config in toolchain.

**Comment by akurtakov** [comment]
Actually tycho deployment didn't happen https://ci.eclipse.org/tycho/job/tycho-github/job/master/419/console . I'll retrigger.

**Comment by akurtakov** [comment]
Nope, Issue697Test failed again. I'll disable the test.

**Pull request merged**
