### PR TITLE
fix for bug 544016

### PR DESCRIPTION
**Pull request by robseidel**
fixes this issue https://bugs.eclipse.org/bugs/show_bug.cgi?id=544016

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=544016

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=544016

**Comment by mickaelistria** [comment]
Tycho does not use pull request. Please contribute using Gerrit: https://wiki.eclipse.org/Tycho/Contributor_Guide#Pushing_to_Gerrit

**Comment by robseidel** [comment]
Ok, took me some time, but now it is in gerrit as well - https://git.eclipse.org/r/#/c/139581/

**Comment by mickaelistria** [comment]
Patch was merged via Gerrit. Thanks!

**Pull request closed without merging**
