### PR TITLE
#519 Provide better feedback to the user about the cause of a failed resolution

### PR DESCRIPTION
**Pull request by laeubi**
This is just a showcase for the EE case, example output is:

```
[INFO] Resolving dependencies of MavenProject: tycho-its-project.compiler.jdt.bree.java8:c.j.b.j.bundle:1.0.0 @ tycho-its/projects/compiler.missing.bree/c.j.b.j.bundle/pom.xml
[ERROR] c.j.b.j.bundle 1.0.0 requires Execution Environment that matches (&(osgi.ee=JavaSE)(version=17)) but the current resolution context uses [a.jre.javase 11.0.0]
[INFO] {osgi.os=linux, osgi.ws=gtk, org.eclipse.update.install.features=true, osgi.arch=x86_64}
[ERROR] Cannot resolve project dependencies:
[ERROR]   Software being installed: c.j.b.j.bundle 1.0.0
[ERROR]   Missing requirement: c.j.b.j.bundle 1.0.0 requires 'osgi.ee; (&(osgi.ee=JavaSE)(version=17))' but it could not be found
[ERROR] 
[ERROR] See https://wiki.eclipse.org/Tycho/Dependency_Resolution_Troubleshooting for help.
[ERROR] Cannot resolve dependencies of MavenProject: tycho-its-project.compiler.jdt.bree.java8:c.j.b.j.bundle:1.0.0 @ projects/compiler.missing.bree/c.j.b.j.bundle/pom.xml: See log for details -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MavenExecutionException
```

As opposed to the plain P2 message: 
> requires 'osgi.ee; (&(osgi.ee=JavaSE)(version=17))' but it could not be found

Tycho now can more specifically tell the user what actually is in use:
> requires Execution Environment that matches (&(osgi.ee=JavaSE)(version=17)) but the current resolution context uses [a.jre.javase 11.0.0]

I also think that enhancing such a message in P2 itself would be hard to archive as it not only requires to examine the missing requirement but also what EE where provided and/or are available.

### CODE REVIEW

**Comment by mickaelistria** [comment]
What happens if one set executionEnvironment=none to enforce usage of JustJ, and tries to build a product that requires Java 17 while only providing JustJ 16?

**Comment by laeubi** [comment]
> What happens if one set executionEnvironment=none to enforce usage of JustJ, and tries to build a product that requires Java 17 while only providing JustJ 16?

I have no idea, is there an example project that demonstrate this use-case?

**Comment by mickaelistria** [comment]
>  I have no idea, is there an example project that demonstrate this use-case?

There is a justj test case in tycho-its. It can maybe be tweaked it to make the issue happen.

**Comment by laeubi** [comment]
Maybe just focus on the obvious cases first?
I can think about several ways to further improve this, some include enhancing P2 but I do not want to put too much effort into this if it is considered not useful and thus just give some examples. If we have agreed on the general aspects we could go into more details I think.

**Comment by mickaelistria** [comment]
> Maybe just focus on the obvious cases first?

I just want to ensure those real use-cases (eg EPP uses it) would not lead to a worse result (eg a NPE instead of a usable error message).

**Comment by laeubi** [comment]
> > Maybe just focus on the obvious cases first?
> 
> I just want to ensure those real use-cases (eg EPP uses it) would not lead to a worse result (eg a NPE instead of a usable error message).

The code does not harm there (resolution simply succeeds) but we get strange error messages in this case from the mojos, I have added a test case here and will try to improve that case.

**Comment by mickaelistria** [comment]
No objection, thank you for testing with JustJ. Feel free to merge.

**Pull request merged**
