### PR TITLE
Enhanced Testcase for #80 to show problem with simpleconfigurator

### PR DESCRIPTION
**Pull request by laeubi**
Enhanced the testcase to include simpleconfigurator (and check it is working)

Signed-off-by: Christoph Läubrich <laeubi@laeubi-soft.de>

### CODE REVIEW

**Comment by mickaelistria** [comment]
I don't think the 2 issues are strongly coupled (they're related but not equivalent), so it would IMO be better to write a separate test for the simpleconfigurator.

**Comment by laeubi** [comment]
Checking for simple configurator is necessary  as it shows that everything works as expected.

**Comment by mickaelistria** [comment]
You're putting a lot of content and checks into a single test. That is not how test scale and help best.
Having 2 different features and test cases would be better here to better identify which part of the functionality is working/failing.

**Comment by laeubi** [comment]
These are not two features! The test check a specific problem and all parts are required to prove a working solution. For sure I can copy the whole test project but this won't save a single line not would it make things more clear. The initial test was simply incomplete.

**Comment by mickaelistria** [comment]
Why is the activemq part necessary to test the simpleconfigurator part?
I'd really rather see that specific simpleconfigurator issue isolated from everything else to better track it specifically, as experiece just showed that the former test does cover 1 story well, and that this story didn't seem to cover the simpleconfigurator well; and the simpleconfigurator part does not require the activemq part to be failing. There are opportunities for 1 test to break independently of the other, so it's better to separate them.

**Comment by laeubi** [comment]
The activemq part is required to actually check that an older version is used (what is not possible with simple-configurator alone), the simple-configurator is required to check, that even if the build succeeds, the product is created as a valid one.
Otherwhise there will be no builderror but the result is (maybe) a brocken product. thats why these both are required to be checked together.

**Comment by mickaelistria** [comment]
So you agree that there are 2 distinct stories: 1 about verifying correct version is used (covered by activemq), and another about properly supporting simpleconfigurator? If so, it confirms to me 2 distinct feature/product/tests would be more profitable.

**Comment by laeubi** [comment]
Obsolete for now.

**Pull request closed without merging**
