### PR TITLE
Update maven.yml

### PR DESCRIPTION
**Pull request by laeubi**
testing in progress - do not merge

### CODE REVIEW

**Comment by laeubi** [comment]
@akurtakov @mickaelistria I have now configured two JDKs in the GH action and configured a toolchains.xml for the maven build but it seems this is not picked up by the integration tests. Is there a trick to define the toolchains.xml for the itests as well?

**Comment by akurtakov** [comment]
Only reason for it to not work I can think of is forking IT tests and thus losing the --global-toolchain parameter. Can you put the file ~/.m2?

**Comment by laeubi** [comment]
That helped for the test but two itests are still failing: https://github.com/eclipse/tycho/runs/3621612714 ... I'll try to investigate tomorrow.

**Comment by laeubi** [comment]
Everything works now, @mickaelistria @akurtakov any concerns that I quash/merge this? This will then include the itests as well.

**Comment by laeubi** [comment]
BTW this would allow us to use other jdks as well if desired.

**Comment by mickaelistria** [comment]
No concern for a squash+merge as soon as you're ready.

**Pull request merged**
