### PR TITLE
Document parallel testing changes (fixes #342)

### LINKED ISSUE #342: Parallelization performance severely degraded since Tycho 1.7.0
We have been using Java 11 / Tycho 1.6.0 in our project since the release of Java 11. 

The build is quite lengthy and, without any special configuration, takes about 3 hours. Therefore we set the `-T 1C` command line option to build several projects in parallel. This logs warnings about unsupported parallelization but has always been working fine. Building in parallel drops the build time to 2 hours.

Anticipating the upcoming Java 17 support I tried upgrading the build system to Tycho 2.4.0 to test for any major roadblocks.

With Tycho 2.4.0 the unparallelized build takes the same 3 hours as with Tycho 1.6.0, but setting the parallelization option actually increases the build time to 3 hours and 47 minutes!

I tested with older versions of Tycho and it seems that the severe slowdown happens since version 1.7.0. I did not expect that - minor changes in the build time are fine, but I expected the build time to stay at least in the area of 2 hours.

||with `-T 1C`|without `-T 1C`|
|---|---|---|
|**Tycho 1.6.0**|2 hours|3 hours|
|**Tycho 1.7.0+**|~4 hours|3 hours|

Going from our current, parallelized, 2 hour build, that is an increase of almost 100 % - but even increasing the build time to 3 hours by building unparallelized is hardly an option.

Is there a problem with running the build parallelized since Tycho 1.7.0? Do I have to configure something differently?

Our maven call looks like this:
`mvn install -Dmaven.repo.local=<repository location> -P <profile name> -T 1C -fae`

The profile just determines which tests are executed and should not behave differently whether the `-T 1C` parameter is present or not.

### PR DESCRIPTION
**Pull request by Bananeweizen**

### CODE REVIEW

**Comment by mickaelistria** [comment]
+1 for updating the doc.
However, on the long run, you may want to add some option to the TestMojo to prevent it from running parallel executions.

**Comment by laeubi** [comment]
Isn't there already a flag (useUIHarness) for UI tests that might be used here?

**Comment by mickaelistria** [comment]
UI tests usually can execute in parallel. It's more some specific tests or frameworks that require to have the window active. Bit tests can usually have other "locks", eg a DB, that can apply.
So useUIHarness doesn't fit as it's not fine-grain enough. I imagine maven-surefire-plugin may have some capabilities about it that Tycho could consume.

**Comment by Bananeweizen** [comment]
Using that flag seems reasonable on first glance. However, you can also run SWTBot tests just to have thread-safe access to controls, without ever using the "click" features etc. Such tests would be fine. Also, I'm not a linux expert, but I would expect to be able to use different virtual screens there where parallel execution would be okay. That's why I would go for something more explicit (which would also be more easy to find in the documentation then).

**Comment by Bananeweizen** [comment]
BTW: Is there some description available for how you committers generally work? Since I had no negative feedback about this PR and since it passed tests, I would now merge it. Or are self-merges of own PRs not okay?

**Comment by laeubi** [comment]
I would then rather not add any options here but let either

- disable parallel execution for such test
- enhance the framework / or use "safe" variants (especially for SWT bot you can construct a bot that only works on a specific window regardless of "active" window)
- use some other kind of synchronization (e.g. lockfiles or similar)

**Comment by laeubi** [comment]
> BTW: Is there some description available for how you committers generally work? Since I had no negative feedback about this PR and since it passed tests, I would now merge it. Or are self-merges of own PRs not okay?

If you are certain that your change is small enough without getting any feedback from others you can merge it, otherwise you can always request a review on it.

**Pull request merged**
