### PR TITLE
Allow parallel execution of compilation and package plugin

### PR DESCRIPTION
**Pull request by jhonnen**
issue #25

### CODE REVIEW

**Comment by mickaelistria** [comment]
Have you audited the code to verify that this mojo executions are actually thread safe?

**Comment by jhonnen** [comment]
Yes, _AFAICT_ there's nothing that requires synchronization. Also I did not see any issues when trying it on our project.

**Comment by mickaelistria** [comment]
OK, I also went through those mojos and didn't figure out some dangerous path for parallelization. Let's merge.

**Comment by mickaelistria** [comment]
This causes https://github.com/eclipse/tycho/issues/183

**Pull request merged**
