### PR TITLE
Delete temporary directory after exit

### PR DESCRIPTION
**Pull request by MarcMil**

### CODE REVIEW

**Comment by MarcMil** [comment]
Argh... I think it's not worth for such a small change to do signing and stuff.
Feel free to do whatever with this code whatever you want or implement it similarly. Eclipse Contributor Agreement is fine, but setting everything up seems like being a bit too much overhead.

**Comment by laeubi** [comment]
@MarcMil Essentially you need to sign the CLA and then simply add "Signed-Off" header to your commit. This should be much more easy now. If your still interested in fixing this let us know.

**Comment by mickaelistria** [comment]
> en simply add "Signed-Off" header to your commit. 

That is not necessary anymore ( https://www.eclipse.org/lists/eclipse.org-committers/msg01291.html ), so all that's required now is to sign ECA with the same email address as the one of the "author" of the commit.

**Comment by MarcMil** [comment]
That's great news. I signed the ECA a minute ago using the E-Mail address of the commit and I hope this comment triggers the validation pass again.

**Comment by laeubi** [comment]
I was not sure if this already was rolled out yet... it might still be necessary to enter the github user ID in your eclipse profile.

**Comment by MarcMil** [comment]
Done.

**Comment by mickaelistria** [comment]
The ECA check doesn't automatically update. But I verified on Eclipse website and could get `There is a valid ECA on file for Marc@Miltenberger.eu.`, so we're good from IP POV.
However, the build reports a compilation issue. Can you please look at it?

**Comment by mickaelistria** [comment]
Rebased and merged as 5feb9379522f3ab0f3cde5be88412cff8d085b2a

**Comment by mickaelistria** [comment]
Rebased and merged as 5feb9379522f3ab0f3cde5be88412cff8d085b2a . Thanks!

**Comment by mickaelistria** [comment]
This did cause #79 and get reverted as df649727c7ed85d573b829a5ac7c92bc7cba5db8

**Pull request closed without merging**
