### PR TITLE
[DEMO] JustJ

### PR DESCRIPTION
**Pull request by mickaelistria**

### CODE REVIEW

**Comment by laeubi** [comment]
@mickaelistria should we merge this? Or maybe move this to the tycho-demo part?

**Comment by mickaelistria** [comment]
It shouldn't be a test because it's toolong to execute, but moving it to demo is a good idea.

**Comment by laeubi** [comment]
@mickaelistria can you update the PR so it is located at the tycho demo then?

**Comment by mickaelistria** [comment]
> can you update the PR so it is located at the tycho demo then?

I'm taken with many other topics to work on and which seem of higher value, so I don't think this is going to be high enough priority for me to work on it anytime soon.

**Comment by akurtakov** [comment]
Please either finish this one or close. Keeping things open for months doesn't help in other ways but to use more infra so the PR is still verified after each commit.

**Comment by mickaelistria** [comment]
https://github.com/eclipse/tycho/commit/498449a244addc614e95904caa59aea1596a936c is merged and shows how to include JustJ in a product and build it with Tycho.

**Pull request closed without merging**
