### PR TITLE
Fix #708 - Ignore local items for tycho builds by default

### LINKED ISSUE #708: Ignore local items for tycho builds by default
As described in #696 sometime releases and snapshots diverge. One problem might be locally build units.

We should change the build and deploy instructions to ignore locally build units, as a default this can the be override if needed (e.g. testing a custom P2 distribution).

### PR DESCRIPTION
**Pull request by laeubi**
Any concerns? This should make local build much more reproducible in case of someone also do some platform development.

### CODE REVIEW

**Comment by mickaelistria** [comment]
I think changing that would suddenly become inconsistent with how Maven behaves. Maven users expect than building A and then building B (that depends on A) will get B seeing the recent changes from A. I don't think it's a good thing to change it by default, unless Maven itself changes it.

**Comment by laeubi** [comment]
this is only for the tycho build (actually tycho-bundles build) so users are not really affected.

**Comment by mickaelistria** [comment]
Still, people who contribute to Tycho would expect to have it work normally and react to change in upstream deps.
If this saves time on CI, this flag would better be set on Jenkinsfile & various GitHub worklows.

**Comment by mickaelistria** [comment]
Still, it's consistent with Maven which IMO matters more than some people being surprised that modifying their local repo can modify their builds.

**Comment by laeubi** [comment]
> Still, it's consistent with Maven which IMO matters more than some people being surprised that modifying their local repo can modify their builds.

I don't agree here. Tycho always chooses the highest version, while maven only matches the *exact* version for local artifact.

**Comment by mickaelistria** [comment]
> Tycho always chooses the highest version, 

Nope, Tycho picks the version that's suggested by p2, which is not necessarily the highest version and actually happens to be the version with the smallest dependency tree in practice.

> maven only matches the exact version for local artifact.

Nope. If your project has multiple transitive dependencies on an artifact, with those dependencies requiring different versions, than Maven will choose one version for it. What Maven will choose depends on what you previously installed in your local Maven repo.

**Comment by laeubi** [comment]
I still think all of this is not relevant for tycho here and harms more than it helps. Anyways if there so so many concern I would simply drop this, but would the ask to work at #698 with some priority to get reliable releases.

**Comment by akurtakov** [comment]
So should this one be closed?

**Pull request closed without merging**
