### PR TITLE
Fix #292 Use POSIX longfile extension

### LINKED ISSUE #292: org.eclipse.tycho.plugins.tar.TarGzArchiverTest currently fails on jenkins ci
@akurtakov @mickaelistria any idea? Is this an OS issue we need to report to ci-infra?

### PR DESCRIPTION
**Pull request by laeubi**
Signed-off-by: Christoph Läubrich <laeubi@laeubi-soft.de>

### CODE REVIEW

**Comment by akurtakov** [comment]
According to http://www.gnu.org/software/tar/manual/html_section/Formats.html gnu format already supports longer uid/gid. So the issue must be smth different.

**Comment by cdietrich** [comment]
do we have a complete stacktrace somewhere?

**Comment by laeubi** [comment]
> do we have a complete stacktrace somewhere?

I scheduled a build with `-DtrimStackTrace=false`

**Comment by laeubi** [comment]
> So the issue must be smth different.

We can try update to 

```
<dependency>
    <groupId>org.apache.commons</groupId>
    <artifactId>commons-compress</artifactId>
    <version>1.21</version>
</dependency>
```

can you open a PR to see if that works?

**Comment by laeubi** [comment]
>  gnu format already supports longer uid/gid

Maybe commons compress only support v7?

> Maximum value of user or group ID is limited to 2097151 (7777777 octal)

**Comment by laeubi** [comment]
Here it also mentioned support for larger UIDs: https://commons.apache.org/proper/commons-compress/apidocs/org/apache/commons/compress/archivers/tar/TarArchiveEntry.html

**Comment by laeubi** [comment]
I will on next commit try to set `tarStream.setBigNumberMode(TarArchiveOutputStream.BIGNUMBER_POSIX);` as well... that might be the "magic" here...

**Comment by laeubi** [comment]
Here is the full stacktrace:

```
[ERROR] org.eclipse.tycho.plugins.tar.TarGzArchiverTest.testSymbolicLinkAbsoluteTargetConvertedToRelative  Time elapsed: 0.002 s  <<< ERROR!
java.lang.IllegalArgumentException: user id '1003220000' is too big ( > 2097151 ).
	at org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.failForBigNumber(TarArchiveOutputStream.java:651)
	at org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.failForBigNumber(TarArchiveOutputStream.java:639)
	at org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.failForBigNumbers(TarArchiveOutputStream.java:630)
	at org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.putArchiveEntry(TarArchiveOutputStream.java:377)
	at org.eclipse.tycho.plugins.tar.TarGzArchiver.addToTarRecursively(TarGzArchiver.java:105)
	at org.eclipse.tycho.plugins.tar.TarGzArchiver.createArchive(TarGzArchiver.java:84)
	at org.eclipse.tycho.plugins.tar.TarGzArchiverTest.testSymbolicLinkAbsoluteTargetConvertedToRelative(TarGzArchiverTest.java:146)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:364)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:272)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:237)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:158)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
```

**Comment by laeubi** [comment]
Cherry-Picked to 2.5.x as well ...

**Pull request merged**
