### PR TITLE
Fix #303 M2E-core build fails with Uses-constraint-violations

### LINKED ISSUE #303: M2E-core build fails with Uses-constraint-violations
The Maven build of m2e-core fails when the latest Tycho 2.5.0-SNAPSHOT is used because the resolution of the Target-Platform fails because of `org.apache.felix.resolver.reason.ReasonException: Uses constraint violations`.

A draft PR in m2e outlines this issue: https://github.com/eclipse-m2e/m2e-core/pull/334:

```
[INFO] Fetching org.w3c.dom.smil_1.0.1.v200903091627.jar from https://download.eclipse.org/eclipse/updates/4.21/R-4.21-202109060500/plugins/ (21.24kB)
[ERROR] Internal error: java.lang.RuntimeException: org.osgi.framework.BundleException: Bundle org.eclipse.m2e.core.ui cannot be resolved:org.eclipse.m2e.core.ui [115]
[ERROR]   Unresolved requirement: Require-Bundle: org.eclipse.m2e.model.edit; bundle-version="[1.16.0,2.0.0)"; visibility:="reexport"
[ERROR]     -> Bundle-SymbolicName: org.eclipse.m2e.model.edit; bundle-version="1.18.2.qualifier"; singleton:="true"
[ERROR]        org.eclipse.m2e.model.edit [116]
[ERROR]          Unresolved requirement: Require-Bundle: org.eclipse.wst.xml.core; visibility:="reexport"
[ERROR]            -> Bundle-SymbolicName: org.eclipse.wst.xml.core; bundle-version="1.2.300.v202102110535"; singleton:="true"
[ERROR]               org.eclipse.wst.xml.core [105]
[ERROR]                 Unresolved requirement: Require-Bundle: org.eclipse.jem.util; bundle-version="[2.1.200,3.0.0)"; resolution:="optional"
[ERROR]                 Unresolved requirement: Require-Bundle: org.eclipse.wst.validation; bundle-version="[1.2.700,1.3.0)"; resolution:="optional"
[ERROR]                 Unresolved requirement: Require-Bundle: org.eclipse.wst.common.emfworkbench.integration; bundle-version="[1.2.100,1.3.0)"; resolution:="optional"
[ERROR]                 Bundle was not resolved because of a uses constraint violation.
[ERROR]   org.apache.felix.resolver.reason.ReasonException: Uses constraint violation. Unable to resolve resource org.eclipse.wst.xml.core [osgi.identity; osgi.identity="org.eclipse.wst.xml.core"; type="osgi.bundle"; version:Version="1.2.300.v202102110535"; singleton:="true"] because it is exposed to package 'org.w3c.dom.events' from resources org.eclipse.osgi [osgi.identity; osgi.identity="org.eclipse.osgi"; type="osgi.bundle"; version:Version="3.17.0.v20210823-1805"; singleton:="true"] and org.w3c.dom.events [osgi.identity; osgi.identity="org.w3c.dom.events"; type="osgi.bundle"; version:Version="3.0.0.draft20060413_v201105210656"] via two dependency chains.
[ERROR] 
[ERROR] Chain 1:
[ERROR]   org.eclipse.wst.xml.core [osgi.identity; osgi.identity="org.eclipse.wst.xml.core"; type="osgi.bundle"; version:Version="1.2.300.v202102110535"; singleton:="true"]
[ERROR]     require: (&(osgi.wiring.bundle=org.eclipse.core.runtime)(&(bundle-version>=3.14.0)(!(bundle-version>=4.0.0))))
[ERROR]      |
[ERROR]     provide: osgi.wiring.bundle: org.eclipse.core.runtime
[ERROR]   org.eclipse.osgi [osgi.identity; osgi.identity="org.eclipse.osgi"; type="osgi.bundle"; version:Version="3.17.0.v20210823-1805"; singleton:="true"]
[ERROR] 
[ERROR] Chain 2:
[ERROR]   org.eclipse.wst.xml.core [osgi.identity; osgi.identity="org.eclipse.wst.xml.core"; type="osgi.bundle"; version:Version="1.2.300.v202102110535"; singleton:="true"]
[ERROR]     require: (&(osgi.wiring.bundle=org.apache.xerces)(&(bundle-version>=2.12.1)(!(bundle-version>=3.0.0))))
[ERROR]      |
[ERROR]     provide: osgi.wiring.bundle; bundle-version:Version="2.12.1.v20210115-0812"; osgi.wiring.bundle="org.apache.xerces"
[ERROR]   org.apache.xerces [osgi.identity; osgi.identity="org.apache.xerces"; type="osgi.bundle"; version:Version="2.12.1.v20210115-0812"]
[ERROR]     import: (osgi.wiring.package=org.w3c.dom.events)
[ERROR]      |
[ERROR]     export: osgi.wiring.package: org.w3c.dom.events
[ERROR]   org.w3c.dom.events [osgi.identity; osgi.identity="org.w3c.dom.events"; type="osgi.bundle"; version:Version="3.0.0.draft20060413_v201105210656"]
[ERROR] -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: java.lang.RuntimeException: org.osgi.framework.BundleException: Bundle org.eclipse.m2e.core.ui cannot be resolved:org.eclipse.m2e.core.ui [115]
  Unresolved requirement: Require-Bundle: org.eclipse.m2e.model.edit; bundle-version="[1.16.0,2.0.0)"; visibility:="reexport"
    -> Bundle-SymbolicName: org.eclipse.m2e.model.edit; bundle-version="1.18.2.qualifier"; singleton:="true"
       org.eclipse.m2e.model.edit [116]
         Unresolved requirement: Require-Bundle: org.eclipse.wst.xml.core; visibility:="reexport"
           -> Bundle-SymbolicName: org.eclipse.wst.xml.core; bundle-version="1.2.300.v202102110535"; singleton:="true"
              org.eclipse.wst.xml.core [105]
                Unresolved requirement: Require-Bundle: org.eclipse.jem.util; bundle-version="[2.1.200,3.0.0)"; resolution:="optional"
                Unresolved requirement: Require-Bundle: org.eclipse.wst.validation; bundle-version="[1.2.700,1.3.0)"; resolution:="optional"
                Unresolved requirement: Require-Bundle: org.eclipse.wst.common.emfworkbench.integration; bundle-version="[1.2.100,1.3.0)"; resolution:="optional"
                Bundle was not resolved because of a uses constraint violation.
  org.apache.felix.resolver.reason.ReasonException: Uses constraint violation. Unable to resolve resource org.eclipse.wst.xml.core [osgi.identity; osgi.identity="org.eclipse.wst.xml.core"; type="osgi.bundle"; version:Version="1.2.300.v202102110535"; singleton:="true"] because it is exposed to package 'org.w3c.dom.events' from resources org.eclipse.osgi [osgi.identity; osgi.identity="org.eclipse.osgi"; type="osgi.bundle"; version:Version="3.17.0.v20210823-1805"; singleton:="true"] and org.w3c.dom.events [osgi.identity; osgi.identity="org.w3c.dom.events"; type="osgi.bundle"; version:Version="3.0.0.draft20060413_v201105210656"] via two dependency chains.

Chain 1:
  org.eclipse.wst.xml.core [osgi.identity; osgi.identity="org.eclipse.wst.xml.core"; type="osgi.bundle"; version:Version="1.2.300.v202102110535"; singleton:="true"]
    require: (&(osgi.wiring.bundle=org.eclipse.core.runtime)(&(bundle-version>=3.14.0)(!(bundle-version>=4.0.0))))
     |
    provide: osgi.wiring.bundle: org.eclipse.core.runtime
  org.eclipse.osgi [osgi.identity; osgi.identity="org.eclipse.osgi"; type="osgi.bundle"; version:Version="3.17.0.v20210823-1805"; singleton:="true"]

Chain 2:
  org.eclipse.wst.xml.core [osgi.identity; osgi.identity="org.eclipse.wst.xml.core"; type="osgi.bundle"; version:Version="1.2.300.v202102110535"; singleton:="true"]
    require: (&(osgi.wiring.bundle=org.apache.xerces)(&(bundle-version>=2.12.1)(!(bundle-version>=3.0.0))))
     |
    provide: osgi.wiring.bundle; bundle-version:Version="2.12.1.v20210115-0812"; osgi.wiring.bundle="org.apache.xerces"
  org.apache.xerces [osgi.identity; osgi.identity="org.apache.xerces"; type="osgi.bundle"; version:Version="2.12.1.v20210115-0812"]
    import: (osgi.wiring.package=org.w3c.dom.events)
     |
    export: osgi.wiring.package: org.w3c.dom.events
  org.w3c.dom.events [osgi.identity; osgi.identity="org.w3c.dom.events"; type="osgi.bundle"; version:Version="3.0.0.draft20060413_v201105210656"]
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:120)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: java.lang.RuntimeException: org.osgi.framework.BundleException: Bundle org.eclipse.m2e.core.ui cannot be resolved:org.eclipse.m2e.core.ui [115]
  Unresolved requirement: Require-Bundle: org.eclipse.m2e.model.edit; bundle-version="[1.16.0,2.0.0)"; visibility:="reexport"
    -> Bundle-SymbolicName: org.eclipse.m2e.model.edit; bundle-version="1.18.2.qualifier"; singleton:="true"
       org.eclipse.m2e.model.edit [116]
         Unresolved requirement: Require-Bundle: org.eclipse.wst.xml.core; visibility:="reexport"
           -> Bundle-SymbolicName: org.eclipse.wst.xml.core; bundle-version="1.2.300.v202102110535"; singleton:="true"
              org.eclipse.wst.xml.core [105]
                Unresolved requirement: Require-Bundle: org.eclipse.jem.util; bundle-version="[2.1.200,3.0.0)"; resolution:="optional"
                Unresolved requirement: Require-Bundle: org.eclipse.wst.validation; bundle-version="[1.2.700,1.3.0)"; resolution:="optional"
                Unresolved requirement: Require-Bundle: org.eclipse.wst.common.emfworkbench.integration; bundle-version="[1.2.100,1.3.0)"; resolution:="optional"
                Bundle was not resolved because of a uses constraint violation.
  org.apache.felix.resolver.reason.ReasonException: Uses constraint violation. Unable to resolve resource org.eclipse.wst.xml.core [osgi.identity; osgi.identity="org.eclipse.wst.xml.core"; type="osgi.bundle"; version:Version="1.2.300.v202102110535"; singleton:="true"] because it is exposed to package 'org.w3c.dom.events' from resources org.eclipse.osgi [osgi.identity; osgi.identity="org.eclipse.osgi"; type="osgi.bundle"; version:Version="3.17.0.v20210823-1805"; singleton:="true"] and org.w3c.dom.events [osgi.identity; osgi.identity="org.w3c.dom.events"; type="osgi.bundle"; version:Version="3.0.0.draft20060413_v201105210656"] via two dependency chains.

Chain 1:
  org.eclipse.wst.xml.core [osgi.identity; osgi.identity="org.eclipse.wst.xml.core"; type="osgi.bundle"; version:Version="1.2.300.v202102110535"; singleton:="true"]
    require: (&(osgi.wiring.bundle=org.eclipse.core.runtime)(&(bundle-version>=3.14.0)(!(bundle-version>=4.0.0))))
     |
    provide: osgi.wiring.bundle: org.eclipse.core.runtime
  org.eclipse.osgi [osgi.identity; osgi.identity="org.eclipse.osgi"; type="osgi.bundle"; version:Version="3.17.0.v20210823-1805"; singleton:="true"]

Chain 2:
  org.eclipse.wst.xml.core [osgi.identity; osgi.identity="org.eclipse.wst.xml.core"; type="osgi.bundle"; version:Version="1.2.300.v202102110535"; singleton:="true"]
    require: (&(osgi.wiring.bundle=org.apache.xerces)(&(bundle-version>=2.12.1)(!(bundle-version>=3.0.0))))
     |
    provide: osgi.wiring.bundle; bundle-version:Version="2.12.1.v20210115-0812"; osgi.wiring.bundle="org.apache.xerces"
  org.apache.xerces [osgi.identity; osgi.identity="org.apache.xerces"; type="osgi.bundle"; version:Version="2.12.1.v20210115-0812"]
    import: (osgi.wiring.package=org.w3c.dom.events)
     |
    export: osgi.wiring.package: org.w3c.dom.events
  org.w3c.dom.events [osgi.identity; osgi.identity="org.w3c.dom.events"; type="osgi.bundle"; version:Version="3.0.0.draft20060413_v201105210656"]
    at org.eclipse.tycho.core.osgitools.OsgiBundleProject.getResolverState (OsgiBundleProject.java:329)
    at org.eclipse.tycho.core.osgitools.OsgiBundleProject.resolveClassPath (OsgiBundleProject.java:196)
    at org.eclipse.tycho.core.resolver.DefaultTychoResolver.resolveProject (DefaultTychoResolver.java:173)
    at org.eclipse.tycho.core.maven.TychoMavenLifecycleParticipant.lambda$resolveProjects$0 (TychoMavenLifecycleParticipant.java:127)
    at java.util.stream.ForEachOps$ForEachOp$OfRef.accept (ForEachOps.java:183)
    at java.util.stream.WhileOps$1$1.accept (WhileOps.java:99)
    at java.util.ArrayList$ArrayListSpliterator.tryAdvance (ArrayList.java:1631)
    at java.util.stream.ReferencePipeline.forEachWithCancel (ReferencePipeline.java:127)
    at java.util.stream.AbstractPipeline.copyIntoWithCancel (AbstractPipeline.java:502)
    at java.util.stream.AbstractPipeline.copyInto (AbstractPipeline.java:488)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto (AbstractPipeline.java:474)
    at java.util.stream.ForEachOps$ForEachOp.evaluateSequential (ForEachOps.java:150)
    at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential (ForEachOps.java:173)
    at java.util.stream.AbstractPipeline.evaluate (AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.forEach (ReferencePipeline.java:497)
    at org.eclipse.tycho.core.maven.TychoMavenLifecycleParticipant.resolveProjects (TychoMavenLifecycleParticipant.java:158)
    at org.eclipse.tycho.core.maven.TychoMavenLifecycleParticipant.afterProjectsRead (TychoMavenLifecycleParticipant.java:102)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:264)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: org.osgi.framework.BundleException: Bundle org.eclipse.m2e.core.ui cannot be resolved:org.eclipse.m2e.core.ui [115]
  Unresolved requirement: Require-Bundle: org.eclipse.m2e.model.edit; bundle-version="[1.16.0,2.0.0)"; visibility:="reexport"
    -> Bundle-SymbolicName: org.eclipse.m2e.model.edit; bundle-version="1.18.2.qualifier"; singleton:="true"
       org.eclipse.m2e.model.edit [116]
         Unresolved requirement: Require-Bundle: org.eclipse.wst.xml.core; visibility:="reexport"
           -> Bundle-SymbolicName: org.eclipse.wst.xml.core; bundle-version="1.2.300.v202102110535"; singleton:="true"
              org.eclipse.wst.xml.core [105]
                Unresolved requirement: Require-Bundle: org.eclipse.jem.util; bundle-version="[2.1.200,3.0.0)"; resolution:="optional"
                Unresolved requirement: Require-Bundle: org.eclipse.wst.validation; bundle-version="[1.2.700,1.3.0)"; resolution:="optional"
                Unresolved requirement: Require-Bundle: org.eclipse.wst.common.emfworkbench.integration; bundle-version="[1.2.100,1.3.0)"; resolution:="optional"
                Bundle was not resolved because of a uses constraint violation.
  org.apache.felix.resolver.reason.ReasonException: Uses constraint violation. Unable to resolve resource org.eclipse.wst.xml.core [osgi.identity; osgi.identity="org.eclipse.wst.xml.core"; type="osgi.bundle"; version:Version="1.2.300.v202102110535"; singleton:="true"] because it is exposed to package 'org.w3c.dom.events' from resources org.eclipse.osgi [osgi.identity; osgi.identity="org.eclipse.osgi"; type="osgi.bundle"; version:Version="3.17.0.v20210823-1805"; singleton:="true"] and org.w3c.dom.events [osgi.identity; osgi.identity="org.w3c.dom.events"; type="osgi.bundle"; version:Version="3.0.0.draft20060413_v201105210656"] via two dependency chains.

Chain 1:
  org.eclipse.wst.xml.core [osgi.identity; osgi.identity="org.eclipse.wst.xml.core"; type="osgi.bundle"; version:Version="1.2.300.v202102110535"; singleton:="true"]
    require: (&(osgi.wiring.bundle=org.eclipse.core.runtime)(&(bundle-version>=3.14.0)(!(bundle-version>=4.0.0))))
     |
    provide: osgi.wiring.bundle: org.eclipse.core.runtime
  org.eclipse.osgi [osgi.identity; osgi.identity="org.eclipse.osgi"; type="osgi.bundle"; version:Version="3.17.0.v20210823-1805"; singleton:="true"]

Chain 2:
  org.eclipse.wst.xml.core [osgi.identity; osgi.identity="org.eclipse.wst.xml.core"; type="osgi.bundle"; version:Version="1.2.300.v202102110535"; singleton:="true"]
    require: (&(osgi.wiring.bundle=org.apache.xerces)(&(bundle-version>=2.12.1)(!(bundle-version>=3.0.0))))
     |
    provide: osgi.wiring.bundle; bundle-version:Version="2.12.1.v20210115-0812"; osgi.wiring.bundle="org.apache.xerces"
  org.apache.xerces [osgi.identity; osgi.identity="org.apache.xerces"; type="osgi.bundle"; version:Version="2.12.1.v20210115-0812"]
    import: (osgi.wiring.package=org.w3c.dom.events)
     |
    export: osgi.wiring.package: org.w3c.dom.events
  org.w3c.dom.events [osgi.identity; osgi.identity="org.w3c.dom.events"; type="osgi.bundle"; version:Version="3.0.0.draft20060413_v201105210656"]
    at org.eclipse.tycho.core.osgitools.EquinoxResolver.assertResolved (EquinoxResolver.java:451)
    at org.eclipse.tycho.core.osgitools.EquinoxResolver.newResolvedState (EquinoxResolver.java:134)
    at org.eclipse.tycho.core.osgitools.OsgiBundleProject.getResolverState (OsgiBundleProject.java:326)
    at org.eclipse.tycho.core.osgitools.OsgiBundleProject.resolveClassPath (OsgiBundleProject.java:196)
    at org.eclipse.tycho.core.resolver.DefaultTychoResolver.resolveProject (DefaultTychoResolver.java:173)
    at org.eclipse.tycho.core.maven.TychoMavenLifecycleParticipant.lambda$resolveProjects$0 (TychoMavenLifecycleParticipant.java:127)
    at java.util.stream.ForEachOps$ForEachOp$OfRef.accept (ForEachOps.java:183)
    at java.util.stream.WhileOps$1$1.accept (WhileOps.java:99)
    at java.util.ArrayList$ArrayListSpliterator.tryAdvance (ArrayList.java:1631)
    at java.util.stream.ReferencePipeline.forEachWithCancel (ReferencePipeline.java:127)
    at java.util.stream.AbstractPipeline.copyIntoWithCancel (AbstractPipeline.java:502)
    at java.util.stream.AbstractPipeline.copyInto (AbstractPipeline.java:488)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto (AbstractPipeline.java:474)
    at java.util.stream.ForEachOps$ForEachOp.evaluateSequential (ForEachOps.java:150)
    at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential (ForEachOps.java:173)
    at java.util.stream.AbstractPipeline.evaluate (AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.forEach (ReferencePipeline.java:497)
    at org.eclipse.tycho.core.maven.TychoMavenLifecycleParticipant.resolveProjects (TychoMavenLifecycleParticipant.java:158)
    at org.eclipse.tycho.core.maven.TychoMavenLifecycleParticipant.afterProjectsRead (TychoMavenLifecycleParticipant.java:102)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:264)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/InternalErrorException
```

### PR DESCRIPTION
**Pull request by laeubi**
Signed-off-by: Christoph Läubrich <laeubi@laeubi-soft.de>

### CODE REVIEW

**Comment by laeubi** [comment]
FYI @HannesWell

**Comment by laeubi** [comment]
The build passes and it fixes the m2e issue but still allows to set all necessary properties for other users if desired. If there are no concerns I'll merge this to 2.5.x and master soon.

**Comment by mickaelistria** [comment]
>  set all necessary properties for other users if desired. 

I don't think any user expressed the need to set those properties; so shouldn't we keep all that internal and undocumented at the moment? Maybe later we'll want another better approach for that, using Maven properties or even mojo configuration (which have the benefit of being able to carry documentation visible in editor).

**Comment by laeubi** [comment]
Given that there are seems to be no settings that "fit all" we should at last have the opportunity to give some configuration property, so there is no real need from a user-perspective as its undesirable to set those but if it is the only option to make the build succeed right now maybe acceptable.

Add them as part of the mojo configuration seems not a good idea as they are "not equinox api" so they should (right now) not be to visible and more act as a last resort until we find a better solution, but we might add a way to set generic properties for the resolver instead.

**Comment by mickaelistria** [comment]
> if it is the only option to make the build succeed right now maybe acceptable.

Is it? Ie can't we just hardcode some settings that make all build pass?

**Comment by laeubi** [comment]
At least the m2e build failed with the previous defaults but your test-builds all succeed, it doesn't hurt much to have a backup if we find other configurations requiring other defaults.
Failing to find "works for all defaults" makes Tycho unusable (slow or failing or both) so from my side it would be to risky to not be able to override those if necessary as a last resort.

**Comment by mickaelistria** [comment]
I don't like the idea of eagerly giving options, especially in a form that's not how Maven configuration works. IMO, we're adding more support effort in the future as some users will start playing with combination we don't even know whether they're supposed to work and how; and we basically let users create workarounds relying on those hacks without having to report their case and contribute, so it's also a risk for the community.
That said, we're in a rush if we want to release soon, so feel free to merge (that's actually a bad thing that a deadline prevents from seeking higher quality in a release...). In the worst case, we'll remove the options later and break people who have started to rely on it too hard.

**Comment by laeubi** [comment]
If you think its better I can remove the remarks from the Relase notes so this becomes a "hidden feature"...

**Comment by mickaelistria** [comment]
Yes, I think it's better to expose it as little as possible. Maybe even comment it in the code as being "not supported for general usage and intended to experimental testing when developing Tycho" to be a bit more dissuasive. Then people who have the need for it and come to the mailing-list can be pointed to the code, start to play with it, but be warned that they should consider discussing their requirement as this solution is not meant to be final.

**Comment by mickaelistria** [comment]
Did you try the examples from https://github.com/eclipse/tycho/issues/213 ? I'm afraid if we add 10s for each module in builds that have hundreds of modules, this will still make Tycho too long to resolve.

**Comment by laeubi** [comment]
> I'm afraid if we add 10s for each module in builds that have hundreds of modules, this will still make Tycho too long to resolve.

That's why you can (now unofficially) configure the timeouts or set a batch-size of one in advance, especially the timeout setting of course depends on the machine running the build... The primary goal is I think that it does not "hang forever" and I think a main goal for 2.6.x should be to further improve here (we might need to convince some projects to use latest tycho snapshot to help tweaking the values)...

**Comment by laeubi** [comment]
Cherry picked to 2.5.x branch as well.

**Pull request merged**
