### PR TITLE
fixed typo in  tycho-versions-plugin error message

### PR DESCRIPTION
**Pull request by daus-salar**
Hallo,

I am sorry, I skipped to create a bug report for that tiny change.

### CODE REVIEW

**Review by laeubi — APPROVED** [review]

**Comment by laeubi** [comment]
> I am sorry, I skipped to create a bug report for that tiny change.

No problem but can you please sign the ECA?

**Comment by daus-salar** [comment]
I am not sure what I have to do. I signed the ECA with my mail address sometime ago and I installed the @eclipse-eca-validation app.

**Comment by mickaelistria** [comment]
Please make sure you completed signing correctly. Maybe a major change happened in ECA and requires to re-sign, or something else went wrong: https://accounts.eclipse.org/user/eca
If this doesn't change anything, we'll escalate to Eclipse Foundation webmasters.

**Comment by daus-salar** [comment]
I am sorry I used the wrong email address.

**Comment by mickaelistria** [comment]
Thanks for the patch!

**Pull request merged**
