### PR TITLE
Task 142 update eclipse installer git hub

### LINKED ISSUE #142: Update Eclipse Installer for Tycho to use github repository
I followed the instructions in https://github.com/eclipse/tycho/blob/master/CONTRIBUTING.md to setup a development environment. The setup fails because the repository https://git.eclipse.org/r/tycho/org.eclipse.tycho doesn't exist:

Cloning Git repo https://git.eclipse.org/r/tycho/org.eclipse.tycho to C:\Eclipse\tycho-master\git\org.eclipse.tycho
java.lang.Exception: org.eclipse.jgit.api.errors.TransportException: https://git.eclipse.org/r/tycho/org.eclipse.tycho: tycho/org.eclipse.tycho unavailable
...

### PR DESCRIPTION
**Pull request by LorenzoBettini**
Closes #142 

I also updated the documentation to specify "HTTPS readonly" if not committer.

I tested the setup locally.

@laeubi if you could please review it

### CODE REVIEW

**Comment by laeubi** [comment]
@LorenzoBettini I think the "read only" should be the default as we are using forks to develop code for tycho also for committer.

@merks is it possible for a setup to use a **fork** of a github repository? The usual workflow for this is the following:

1. goto the repository
2. fork it into private account
3. checkout the fork
4. add the original one as 'upstream' in the config

While 1+2 might not be possible to archive, maybe one could have a (required) field `GitHub username/organisation` then use this variable in the git:GitCloneTask and also adding the original one as 'upstream'?

**Comment by merks** [comment]
I'm not totally sure.  The remoteURI property is used and is generally specified as a relative path that is expanded based on choices that are automatically synthesized.  The user is presented these choices, but I think they can paste in a link to a clone which I think would then check out that fork.  It wouldn't configure the upstream thing automatically except maybe the fork itself already specifies that somehow?  But the Git Clone task also support Config Section and stuff nested under there to configure this type of thing...

If something else is needed GitCloneTaskImpl could be extended with new optional attribute to do additional things...

**Comment by laeubi** [comment]
@LorenzoBettini can you check if this is possible with the hints of @merks ?

**Comment by LorenzoBettini** [comment]
@laeubi concerning the fork one could simply paste the URI of his/her fork in the dialog, as @merks said.
Concerning the "read only" by default I don't know how to do that... @merks some hints please?

**Comment by laeubi** [comment]
Yeah I just think we should make this an explicit, non default, required field something like 'forkName', and the checkout task should add the 'upstream' https://github.com/eclipse/tycho.git as an additional origin.

**Comment by LorenzoBettini** [comment]
@laeubi currently I'm unable to do that but I also find it overkill... I'd merge the PR since at least it fixes the current state. Note that the behavior is the same as the old one when the Git repo was hosted on Gerrit. The fork thing is a general GitHub workflow so that's something that possible contributors are already aware of.

**Comment by merks** [comment]
> 
> 
> @laeubi concerning the fork one could simply paste the URI of his/her fork in the dialog, as @merks said.
> Concerning the "read only" by default I don't know how to do that... @merks some hints please?

By this you mean the order in which the choices are listed (where the first choice is then the default).  Those choices are induced from this variable definition in the Project Catalog;
```
<?xml version="1.0" encoding="UTF-8"?>
<setup:VariableTask
    xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:setup="http://www.eclipse.org/oomph/setup/1.0"
    name="github.remoteURIs"
    label="Github repository">
  <choice value="git@github.com:@{remoteURI}.git"
      label="Git (read-write)"/>
  <choice value="https://${github.user.id|username}@github.com/@{remoteURI}.git"
      label="HTTPS (read-write)">
    <annotation
        source="http://www.eclipse.org/oomph/setup/MatchChoice"/>
  </choice>
  <choice value="https://github.com/@{remoteURI}.git"
      label="HTTPS (read-only, anonymous)"/>
  <description>Choose from the available Github URIs</description>
</setup:VariableTask>
```
You could copy and paste that into your setup to change the order...

(Note that you can literally copy the selected XML above  and paste it into your Project in the Setup Editor.)

**Comment by laeubi** [comment]
> Note that the behavior is the same as the old one when the Git repo was hosted on Gerrit. 

That's not really true. Gerrit does not use the concept of Forks/PRs but you have to checkout the code 'readonly' as a non-contributor and then can only submit 'changesets' by everyone with an gerrit-account. These changes never show up in the original git repo if not merged by a contributor. To make this workflow work, there was a special 'gerrit-configuration' in the checked out repository.

That's why I said that if the original URL is used, then it should be read-only to make this more 'gerrit-like'. 

As an alternative, we need to checkout the 'writeable' fork of the user and add a special 'github-workflow' config, otherwhise users using the setup need to pay special attention to reconfigure the push/pull URLs and origins to match their fork.

**Comment by laeubi** [comment]
@LorenzoBettini any plans to further improve this or should we merge this 'as-is'

**Comment by LorenzoBettini** [comment]
@laeubi I'd suggest merging this as it is (as you see, I've also updated the documentation); I currently don't have time to improve it further at moment, but, as I said, I think also in the current shape it's perfectly fine and it's similar to other Oomph setups based on GitHub...

**Comment by laeubi** [comment]
Okay I'll trigger a build then and merge it afterwards (just to get all checks green).

**Pull request merged**
