### PR TITLE
Issue #626 - add integration test

### PR DESCRIPTION
**Pull request by laeubi**
Signed-off-by: Christoph Läubrich <laeubi@laeubi-soft.de>

### CODE REVIEW

**Comment by laeubi** [comment]
```
[DEBUG] Slice:
  org.eclipse.equinox.registry 3.11.0.v20210723-1953
  org.eclipse.core.runtime 3.23.0.v20210730-2035
  org.eclipse.core.contenttype 3.8.0.v20210621-0954
  org.eclipse.equinox.app 1.6.0.v20210723-1130
  org.eclipse.equinox.preferences 3.9.0.v20210726-0943
  org.eclipse.osgi.services 3.10.200.v20210723-0643
  org.eclipse.osgi 3.17.0.v20210823-1805
  org.eclipse.jgit 5.13.0.202109080827-r
  org.eclipse.pde.ds.lib 1.1.500.v20210209-1250
  org.slf4j.api 1.7.30.v20200204-2150
  org.eclipse.core.jobs 3.12.0.v20210723-1034
  com.jcraft.jsch 0.1.55.v20190404-1902
  org.eclipse.equinox.common 3.15.0.v20210518-0604
  org.eclipse.osgi.util 3.6.100.v20210723-1119
  a.jre.javase 11.0.0
  compiler.fragments 1.0.0
  javaewah 1.1.12.v20210622-2206

[DEBUG] Resolved IUs:
  com.jcraft.jsch 0.1.55.v20190404-1902
  a.jre.javase 11.0.0
  compiler.fragments 1.0.0
  org.eclipse.core.runtime 3.23.0.v20210730-2035
  org.eclipse.jgit 5.13.0.202109080827-r
  javaewah 1.1.12.v20210622-2206
  org.eclipse.core.contenttype 3.8.0.v20210621-0954
  org.eclipse.equinox.preferences 3.9.0.v20210726-0943
  org.eclipse.equinox.registry 3.11.0.v20210723-1953
  org.eclipse.equinox.common 3.15.0.v20210518-0604
  org.eclipse.osgi 3.17.0.v20210823-1805
  org.eclipse.core.jobs 3.12.0.v20210723-1034
  org.eclipse.equinox.app 1.6.0.v20210723-1130
  org.slf4j.api 1.7.30.v20200204-2150

[DEBUG] [main] Resolved target platform for MavenProject: tycho.its:compiler.fragments:1.0.0 @ compiler.fragments/pom.xml
  Target environment: linux/gtk/x86_64
  eclipse-plugin:com.jcraft.jsch:0.1.55.v20190404-1902: null
  eclipse-plugin:compiler.fragments:1.0.0: MavenProject: tycho.its:compiler.fragments:1.0.0 @ compiler.fragments/pom.xml
  eclipse-plugin:org.eclipse.core.runtime:3.23.0.v20210730-2035: null
  eclipse-plugin:org.eclipse.jgit:5.13.0.202109080827-r: null
  eclipse-plugin:javaewah:1.1.12.v20210622-2206: null
  eclipse-plugin:org.eclipse.core.contenttype:3.8.0.v20210621-0954: null
  eclipse-plugin:org.eclipse.equinox.preferences:3.9.0.v20210726-0943: null
  eclipse-plugin:org.eclipse.equinox.registry:3.11.0.v20210723-1953: null
  eclipse-plugin:org.eclipse.equinox.common:3.15.0.v20210518-0604: null
  eclipse-plugin:org.eclipse.osgi:3.17.0.v20210823-1805: null
  eclipse-plugin:org.eclipse.core.jobs:3.12.0.v20210723-1034: null
  eclipse-plugin:org.eclipse.equinox.app:1.6.0.v20210723-1130: null
  eclipse-plugin:org.slf4j.api:1.7.30.v20200204-2150: null
```

**Comment by laeubi** [comment]
Missing from the resolution result is: `org.eclipse.jgit.ssh.jsch 5.13.0.202109080827-r`but its part of the target platform content.

@merks do you have an idea what tycho misses here in its configuration to get the required fragments? Or are fragments never considered by P2 as a requirement?

https://github.com/eclipse/tycho/blob/master/tycho-bundles/org.eclipse.tycho.p2.resolver.impl/src/main/java/org/eclipse/tycho/p2/util/resolution/ProjectorResolutionStrategy.java

**Comment by merks** [comment]
A host bundle does not normally require any of its fragments.  I say "normally" because it is possible to express such requirements:

https://git.eclipse.org/c/platform/eclipse.platform.swt.git/tree/bundles/org.eclipse.swt/META-INF/p2.inf

But then one needs to add filters such that the requirement doesn't cause problems while building.

In any case, the requirements on fragments generally/normally come from a feature.xml including the fragment, e.g., 

https://git.eclipse.org/c/equinox/rt.equinox.bundles.git/tree/features/org.eclipse.equinox.core.sdk/feature.xml#n200

And note that for os/arch/ws specific fragments, they have filters such that they are only installed/required on the appropriate platform.

**Comment by laeubi** [comment]
> A host bundle does not normally require any of its fragments

Thanks Ed for validating that, I was afraid of that but was not sure. I think it makes sense from P2 perspective and tycho has to collect the fragments itself for classpath computation.

> because it is possible to express such requirements:

While it makes sense for SWT, I think its not in general a good idea to require fragments.

> note that for os/arch/ws specific fragments, they have filters such that they are only installed/required on the appropriate platform.

That already works as far as I can tell.

**Comment by laeubi** [comment]
@mickaelistria all tests pass so this is ready to be merged.

**Comment by laeubi** [comment]
@mickaelistria if there are no concern I'd like to merge this, the eclipse CI is still wrecked ...

**Comment by mickaelistria** [comment]
I've expressed my concerns earlier, but don't think they are blockers. Feel free to merge, in worst case (eg it makes Platform build fail) we'll adapt or revert if no better solution is found.

**Comment by laeubi** [comment]
Alright lets see how this will work, we can still add an option to disable this if necessary.

**Pull request merged**
