### PR TITLE
Log all events also from the OSGi Log system

### PR DESCRIPTION
**Pull request by laeubi**

### CODE REVIEW

**Comment by laeubi** [comment]
This shows some error output here:
```
java.lang.NullPointerException: Cannot invoke "java.net.URI.getScheme()" because the return value of "org.eclipse.equinox.internal.p2.artifact.repository.simple.SimpleArtifactRepository.getLocation()" is null
    at org.eclipse.equinox.internal.p2.artifact.repository.simple.SimpleArtifactRepository.isLocal (SimpleArtifactRepository.java:1150)
    at org.eclipse.equinox.internal.p2.artifact.repository.simple.SimpleArtifactRepository.isModifiable (SimpleArtifactRepository.java:1155)
    at org.eclipse.equinox.internal.p2.artifact.repository.simple.XZedSimpleArtifactRepositoryFactory.load (XZedSimpleArtifactRepositoryFactory.java:96)
    at org.eclipse.equinox.internal.p2.artifact.repository.simple.XZedSimpleArtifactRepositoryFactory.load (XZedSimpleArtifactRepositoryFactory.java:42)
    at org.eclipse.equinox.internal.p2.artifact.repository.ArtifactRepositoryManager.factoryLoad (ArtifactRepositoryManager.java:92)
    at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository (AbstractRepositoryManager.java:787)
    at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository (AbstractRepositoryManager.java:685)
    at org.eclipse.equinox.internal.p2.artifact.repository.ArtifactRepositoryManager.loadRepository (ArtifactRepositoryManager.java:131)
    at org.eclipse.equinox.p2.internal.repository.tools.RecreateRepositoryApplication.initialize (RecreateRepositoryApplication.java:67)
    at org.eclipse.equinox.p2.internal.repository.tools.RecreateRepositoryApplication.run (RecreateRepositoryApplication.java:46)
    at org.eclipse.tycho.p2.tools.mirroring.MirrorApplicationServiceImpl.recreateArtifactRepository (MirrorApplicationServiceImpl.java:214)
    at org.eclipse.tycho.plugins.p2.repository.FixArtifactsMetadataMetadataMojo.execute (FixArtifactsMetadataMetadataMojo.java:81)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:370)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:351)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:171)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:163)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:294)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:77)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:568)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
```
Need to investigate if this is a Tycho issue or a P2 issue, it seems the error was previously hidden because we do not show errors reported in the Tycho-OSGi part as far as I can see.

**Comment by laeubi** [comment]
P2 issue: https://github.com/eclipse-equinox/p2/issues/124 wil implement a workaround here by deleting the xz'ed data first as it is recreated anyways...

**Comment by rgrunber** [comment]
```
[INFO] --- tycho-p2-repository-plugin:3.0.1:assemble-repository (assemble-repository) @ org.eclipse.lsp4mp.jdt.site ---
[ERROR] [13bf1f08-678d-4029-88b9-000a5deaa2c3][extension>org.eclipse.tycho:tycho-maven-plugin:3.0.1] Unexpected error loading extension: org.eclipse.equinox.p2.artifact.repository.XZedRepository
java.lang.NullPointerException: Cannot invoke "java.net.URI.getScheme()" because the return value of "org.eclipse.equinox.internal.p2.artifact.repository.simple.SimpleArtifactRepository.getLocation()" is null
```

@laeubi , I just ran into this change with Tycho 3.0.1. Is it safe to consume the assemble-repository content of a 3.0.1 tycho-repository-plugin ? Looks to only fail to read it, but the content seems fine and the build succeeded. If this error existed and was hidden even in, say 2.7.2, then I would guess it's fine.

**Comment by laeubi** [comment]
Can you give the whole stacktrace of the error here or provide an [integration-test](https://github.com/eclipse/tycho/wiki#providing-an-integration-test) to demonstrate the issue?

**Comment by rgrunber** [comment]
<details>
<summary>stacktrace</summary>

```
[INFO] 
[INFO] --- tycho-p2-repository-plugin:3.0.1:archive-repository (default-archive-repository) @ org.eclipse.lsp4mp.jdt.site ---
[INFO] Building zip: /home/rgrunber/git/lsp4mp/microprofile.jdt/org.eclipse.lsp4mp.jdt.site/target/org.eclipse.lsp4mp.jdt.site-0.7.0-SNAPSHOT.zip
[INFO] 
[INFO] --- tycho-p2-repository-plugin:3.0.1:assemble-repository (assemble-repository) @ org.eclipse.lsp4mp.jdt.site ---
[ERROR] [380ac475-4048-4634-a02c-bfc583a5e208][extension>org.eclipse.tycho:tycho-maven-plugin:3.0.1] Unexpected error loading extension: org.eclipse.equinox.p2.artifact.repository.XZedRepository
java.lang.NullPointerException: Cannot invoke "java.net.URI.getScheme()" because the return value of "org.eclipse.equinox.internal.p2.artifact.repository.simple.SimpleArtifactRepository.getLocation()" is null
    at org.eclipse.equinox.internal.p2.artifact.repository.simple.SimpleArtifactRepository.isLocal (SimpleArtifactRepository.java:1150)
    at org.eclipse.equinox.internal.p2.artifact.repository.simple.SimpleArtifactRepository.isModifiable (SimpleArtifactRepository.java:1155)
    at org.eclipse.equinox.internal.p2.artifact.repository.simple.XZedSimpleArtifactRepositoryFactory.load (XZedSimpleArtifactRepositoryFactory.java:96)
    at org.eclipse.equinox.internal.p2.artifact.repository.simple.XZedSimpleArtifactRepositoryFactory.load (XZedSimpleArtifactRepositoryFactory.java:42)
    at org.eclipse.equinox.internal.p2.artifact.repository.ArtifactRepositoryManager.factoryLoad (ArtifactRepositoryManager.java:92)
    at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository (AbstractRepositoryManager.java:787)
    at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository (AbstractRepositoryManager.java:685)
    at org.eclipse.equinox.internal.p2.artifact.repository.ArtifactRepositoryManager.loadRepository (ArtifactRepositoryManager.java:131)
    at org.eclipse.equinox.p2.internal.repository.tools.AbstractApplication.addRepository (AbstractApplication.java:156)
    at org.eclipse.equinox.p2.internal.repository.tools.AbstractApplication.initializeDestination (AbstractApplication.java:228)
    at org.eclipse.tycho.p2.tools.mirroring.MirrorApplication.initializeDestination (MirrorApplication.java:72)
    at org.eclipse.equinox.p2.internal.repository.tools.AbstractApplication.processDestinationRepos (AbstractApplication.java:174)
    at org.eclipse.equinox.p2.internal.repository.tools.AbstractApplication.initializeRepos (AbstractApplication.java:138)
    at org.eclipse.equinox.p2.internal.repository.tools.MirrorApplication.run (MirrorApplication.java:200)
    at org.eclipse.tycho.p2.tools.mirroring.MirrorApplicationServiceImpl.mirrorReactor (MirrorApplicationServiceImpl.java:175)
    at org.eclipse.tycho.plugins.p2.repository.AssembleRepositoryMojo.execute (AssembleRepositoryMojo.java:217)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:972)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:77)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:568)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for microprofile.jdt.ls :: parent 0.7.0-SNAPSHOT:
[INFO] 
[INFO] microprofile.jdt.ls :: parent ...................... SUCCESS [  0.055 s]
[INFO] MicroProfile JDT LS Extension ...................... SUCCESS [  8.235 s]
[INFO] lsp4mp :: Target Platform .......................... SUCCESS [  0.003 s]
[INFO] microprofile.jdt.ls :: test ........................ SUCCESS [  4.765 s]
[INFO] microprofile.jdt.ls :: update site ................. SUCCESS [  2.137 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  36.176 s
[INFO] Finished at: 2022-12-08T09:06:08-05:00
[INFO] ------------------------------------------------------------------------
```
</details>

**Comment by laeubi** [comment]
This seems to be
- https://github.com/eclipse-equinox/p2/issues/124

will be fixed on next p2 release but I can't remember what was the root cause triggering this.

**Comment by rgrunber** [comment]
Is it safe to use the content generated when this error occurs ? I remember you mentioned that this is only showing because you exposed some of the errors happening on the OSGi side to the log output ? So is there a chance this was happening all along but completely hidden ? To me it looks like it just fails to read the repository at some point but I'm not seeing content content being invalid.

**Comment by laeubi** [comment]
It depends a bit how you used this, but if your build works everything should be fine, actually there was a workaround applied so p2 do not try to read the xz'ed repo so it a bit strange that you see the error and would be interesting how to reproduce this.

**Comment by rgrunber** [comment]
If interested, it's the PR https://github.com/eclipse/lsp4mp/pull/331 and running `mvn clean verify -f microprofile.jdt/pom.xml -DskipTests` (can also add -Dmaven.repo.local=... to confirm nothing else interferes).

**Pull request merged**
