### PR TITLE
[2.7.0] Fix for performance regression #719

### PR DESCRIPTION
**Pull request by sratz**
Backport from 3.x.

### CODE REVIEW

**Comment by laeubi** [comment]
@sratz thanks for the backport, lets see if we can get the CI working again :-)

**Comment by laeubi** [comment]
@sratz one test fails due an autdated repository ref: https://ci.eclipse.org/tycho/job/tycho-github/job/PR-810/2/testReport/org.eclipse.tycho.test.p2Repository/P2RepositoryPropertiesTest/testPropertyPropagation/

do you like to simply fix this with your commit also?

**Comment by laeubi** [comment]
@sratz can you rebase manually? I should have fixed the issues with the build now.

**Comment by sratz** [comment]
Still some issues in integration tests.

There are several pom.xml files that define a `<tycho-version>` property that is outdated.

**Comment by laeubi** [comment]
Build is now ready for 2.7.1: https://ci.eclipse.org/tycho/job/tycho-github/job/tycho-2.7.x/ but ci is incredible slow...

**Comment by laeubi** [comment]
@sratz can you rebase and and also add a note about the backported for to the release notes with your PR?

**Comment by laeubi** [comment]
many thanks for back porting this, this should hopefully soon (~1h) show up in the [tycho snapshot](https://github.com/eclipse/tycho/wiki#getting-tycho-snapshots) builds.

**Pull request merged**
