### PR TITLE
issue #350 reproducer

### PR DESCRIPTION
**Pull request by jonahgraham**
A ClassCastException is thrown when tycho-p2-repository-plugin is run

I haven't verified that the Java fails as expected yet, but doing:

```
mvn clean verify -Dtycho-version=2.7.0
```
in tycho-its/projects/TYCHO350ClassCastException causes this error:

> [ERROR] Failed to execute goal org.eclipse.tycho:tycho-p2-repository-plugin:2.7.0:fix-artifacts-metadata (fix-p2-repository) on project build: Execution fix-p2-repository of goal org.eclipse.tycho:tycho-p2-repository-plugin:2.7.0:fix-artifacts-metadata failed: java.lang.ClassCastException: class org.eclipse.tycho.core.osgitools.DefaultReactorProject cannot be cast to class org.eclipse.tycho.ReactorProject (org.eclipse.tycho.core.osgitools.DefaultReactorProject is in unnamed module of loader org.codehaus.plexus.classworlds.realm.ClassRealm @665522c2; org.eclipse.tycho.ReactorProject is in unnamed module of loader org.codehaus.plexus.classworlds.realm.ClassRealm @3dd750ba) -> [Help 1]

### CODE REVIEW

**Comment by jonahgraham** [comment]
Reproducer for #350

**Comment by laeubi** [comment]
@jonahgraham I think this can be fixed by adding the tycho-maven plugin to your pom, can you try that out and use it as a workaround until this is fixed?

**Comment by laeubi** [comment]
@jonahgraham can you please rebase on current master?

**Comment by laeubi** [comment]
Thanks. If you do not enable "allow edit by maintainers" then automatic rebase do not work.

**Comment by laeubi** [comment]
@jonahgraham thanks for the reproducer, this is now included in https://github.com/eclipse/tycho/pull/1221 and will hopefully be fixed soon.

**Pull request closed without merging**
