### PR TITLE
Issue  #611 Support setting CI-Friendly-Versions in tycho-build-extension

### PR DESCRIPTION
**Pull request by laeubi**
Add a first implementation and integration test.

### CODE REVIEW

**Comment by laeubi** [comment]
FYI @mickaelistria @akurtakov this will make it possible to have easier deployments of stuff with a simple `mvn deploy -Dtycho.buildqualifier.format=yyyyMMddHHmm` where the -SNAPSHOT is then replaced with `.<buildqualifier>` in the maven build (and hopefully then also in the P2 metadata with valid references), I have only tested this with the very basic integrationtest example but like to merge this as a starting point so we can start to play around with it, I'll add some documentation and see if I can enable git-timestamps easily and then it should be fine as a first iteration I think if there are no concerns.

**One important note:** this strictly requires Maven 3.8.5+ and even if we seem to enforce this in the pom I don't see that maven complains when running with an older version...

**Comment by laeubi** [comment]
Documentation and Jgit support added!

**Comment by laeubi** [comment]
This also includes some cleanup and enhancements to JGIt + Build timestamp, I might try to eplit these from the current change...

**Comment by laeubi** [comment]
Trying to split things actually do not make this more readable as some changes are only inspired by the new functionality, if the build succeeds I'd plan to merge this.

**Comment by mickaelistria** [comment]
That's a major progress. Thanks for that!

**Pull request merged**
