### PR TITLE
Potential fix for Feature request 389757

### PR DESCRIPTION
**Pull request by tomsontom**
OSGi-Application
- allow to launch other OSGi-Applications while running the headless
  application

### CODE REVIEW

**Comment by laeubi** [comment]
@tomsontom is this still relevant for you?

**Comment by tomsontom** [comment]
We switched to pure maven builds in our company so not for us but for others building e4 on JavaFX apps using PDE and tycho it might still be relevant.

**Comment by laeubi** [comment]
Can you explain what this change actually does? Will it harm anything? Is there an example that show how to use it?

**Comment by mickaelistria** [comment]
This was already fixed a long time ago with https://git.eclipse.org/c/tycho/org.eclipse.tycho.git/commit/?id=124d9800167de7c90e75d5f7bc9b8b8584cd84da

**Pull request closed without merging**
