### PR TITLE
Update extensions.xml

### PR DESCRIPTION
**Pull request by laeubi**
Maven 3.8.5 finally supports a placeholder here.

### CODE REVIEW

**Comment by laeubi** [comment]
On the jenkis `apache-maven-latest` is still 3.8.4 so we have to wait with this a bit more... but the GH action already shows that this will work then.

**Comment by laeubi** [comment]
> On the jenkis `apache-maven-latest` is still 3.8.4 so we have to wait with this a bit more...

It obviously would be possible to just set `apache-maven-3.8.5` as a requirements here...

**Comment by akurtakov** [comment]
Could https://ci.eclipse.org/tycho/job/tycho-github/view/change-requests/job/PR-866/12/console be related ?

**Comment by mickaelistria** [comment]
> Could https://ci.eclipse.org/tycho/job/tycho-github/view/change-requests/job/PR-866/12/console be related ?

Nope. I enabled option to cleanup workspace before checkout (from Jenkins job config), and it seems to work better.

**Comment by laeubi** [comment]
Sadly sometimes the downloads get wrecked because of network problems. The builds produce a huge amount of network traffic, for the buildnode I have setup I see a total of 28 GB already transferred the last days...

**Pull request merged**
