### PR TITLE
Test the windows build

### PR DESCRIPTION
**Pull request by laeubi**

### CODE REVIEW

**Comment by laeubi** [comment]
@pzi-dsa Any idea why this maven call on windows seem to fail on windows:

https://github.com/eclipse/tycho/runs/7625048441?check_suite_focus=true

It seems some who windows don't like the `-Dmaven.test.failure.ignore=true` but as we use this on other GH builds as well I'm a bit lost here...

**Comment by pzi-dsa** [comment]
> It seems some who windows don't like the -Dmaven.test.failure.ignore=true but as we use this on other GH builds as well I'm a bit lost here...

I think this is a PowerShell issue rather than a Windows issue. At least that is my experience with Maven so far.
I'd suggest adding a space so that it's `-D maven.test.failure.ignore=true`

**Comment by laeubi** [comment]
> I'd suggest adding a space so that it's `-D maven.test.failure.ignore=true`

Thanks I'll try that never know that it also accepts spaces here ...

**Comment by cdietrich** [comment]
an alternative would be to quote the arg `'-Dmaven.test.failure.ignore=true' `

**Pull request merged**
