### PR TITLE
Cannot build sub module separately with 2.7.3

### PR DESCRIPTION
**Pull request by selundqma**
1.  Clean the m2 folder

2. SUCCESS CASE

Build from the "selundqma" root folder:
**mvn clean install -U -Dtycho.localArtifacts=ignore -Dtycho-version=2.6.0**

Then immediately after that build in the "clients" folder
**mvn clean install -U -Dtycho.localArtifacts=ignore -Dtycho-version=2.6.0**

That worked fine didn´t it? :)

3. Clean the m2 folder

4. FAIL CASE

Build from the "selundqma" folder:
**mvn clean install -U -Dtycho.localArtifacts=ignore -Dtycho-version=2.7.3**

Then immediately after that build in the "clients" folder
**mvn clean install -U -Dtycho.localArtifacts=ignore -Dtycho-version=2.7.3**

Here you should see the error:

[INFO] Resolving class path of com.selundqma.ub.ga.impl...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for bord-parent 22.7.1-SNAPSHOT:
[INFO]
[INFO] bord-parent ........................................ SUCCESS [  0.570 s]
[INFO] com.selundqma.ub.parent ............................ SUCCESS [  0.103 s]
[INFO] com.selundqma.ub.ga.impl ........................... FAILURE [  3.116 s]
[INFO] com.selundqma.ub.feature ........................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  31.281 s
[INFO] Finished at: 2022-06-21T09:59:40+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:2.7.3:validate-classpath (default-validate-classpath) on project com.selundqma.ub.ga.impl: Execution default-validate-classpath of goal org.eclipse.tycho:tycho-compiler-plugin:2.7.3:validate-classpath failed: Exception parsing OSGi MANIFEST C:\m2\repository\com\selundqma\client\client-common\com.selundqma.cs.client.common.feature\22.7.1-SNAPSHOT\com.selundqma.cs.client.common.feature-22.7.1-SNAPSHOT.jar!/META-INF/MANIFEST.MF: MANIFEST header 'Bundle-Version' not found -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :com.selundqma.ub.ga.impl

### CODE REVIEW

**Comment by laeubi** [comment]
@selundqma thanks for providing the test-case, do you think it could be further reduced? e.g. most of the time the .project, classpath and alike are not strictly required if only executed from the commandline. Also the target file seems quite large, is all this really required to reproduce the problem or could it be reproduced e.g. with just the sdk feature?

Beside that, to show up in the build, you have to add a Test-Class that issues the actual maven calls using a `verifier.verifyErrorFreeLog()`

**Comment by selundqma** [comment]
Hi @laeubi ! Oh there was a lot of files to remove.. sorry about that! I also added a Test Class but I didn´t try it locally before submitting it. Now I see the build failed (as I expected due to not testing locally first), but I am not sure what the build error really means. I will have to investigate :).

**Comment by laeubi** [comment]
It seems, the eclipse infra encountering errors, lets see if Github CI can do better :-)

**Comment by laeubi** [comment]
It seems there are infra-issues everywhere now :-D

**Comment by laeubi** [comment]
Is this the failure you expect: https://ci.eclipse.org/tycho/job/tycho-github/job/PR-1057/5/testReport/org.eclipse.tycho.test.SeLundqma/SeLundqmaTest/test/ ?

**Comment by laeubi** [comment]
The problem here is, that the feature is considered to be a plugin (what obviously makes no sense) and thus can't parse the manifest because features do not have such headers.

**Comment by laeubi** [comment]
@selundqma can you please "squash" your two commits and force push the branch?

**Comment by laeubi** [comment]
@selundqma if you squash and rebase your commit then it should run fine and we can integrate the test-case into tycho.

**Comment by laeubi** [comment]
Poor mans rebase:

1. Make sure you have commited everything to your "bad branch"
2. switch to master and create a new branch 
3. The in eclipse do Team> Merge and choose "squash" and your "bad" branch
4. Now all your changes are applied and you can add them to the index and push the branch to the remote

**Comment by laeubi** [comment]
@selundqma thanks for providing this useful test-case!

**Comment by selundqma** [comment]
Thank you for all lovely help!!! And for the very quick fix! Do you think this will be available in a 2.7.4 release or in the upcoming 3.0.0?

**Comment by laeubi** [comment]
It should be already available in 2.7.4-SNAPSHOT you can try out the current [tycho snapshot](https://github.com/eclipse/tycho/wiki#getting-tycho-snapshots) build to verify this.

**Pull request merged**
