### PR TITLE
#55 - discard packaging of test-fragment

### PR DESCRIPTION
**Pull request by laeubi**
Signed-off-by: Christoph Läubrich <laeubi@laeubi-soft.de>

### CODE REVIEW

**Comment by akurtakov** [comment]
What is the reason behind this? There are projects (like Platform, CDT, Linux Tools) that use test fragments and publish them to p2 repository so they can be installed later in a provisioned IDE and executed on different OS/WS/ARCH combo without rebuilding everything.

**Comment by mickaelistria** [comment]
I also don't get why removing this now. Please add explanation in the commit message.

**Comment by laeubi** [comment]
This was recently added by me to package classes in target/test-classes (what was previously empty) and generates some kind of generic Manifest, but I found that my initial idea was not ideal and its original intent becomes a bit obsolete now as PDE refuses to allow something similar in the IDE it does not make sense to go this path further and instead I'd https://github.com/eclipse/tycho/issues/53 will replace this.

So no worries this does not affect existing use-case.

**Comment by mickaelistria** [comment]
OK, please just add those explanation to the commit message, also fix related tests and then feel free to merge as soon as CI is green.
Could it be a revert of https://github.com/eclipse/tycho/commit/d9a58240820776f11feb0a8dbaabfaaa00a4619d ?

**Comment by laeubi** [comment]
I'll do as soon as the replacement for additional bundles is in place, just wanted to see if I break more than these three test cases :-)

The original commit was https://github.com/eclipse/tycho/commit/9485693f128bf3a634f657f0df6e27daab60fbdf but I think we could keep the extraction of manifest creation as it makes code more clear so I decided to not revert this completely.

**Comment by laeubi** [comment]
Two test are failing but recent discussions have show that there is no way to support this, so I'll remove the failing test as they are invalid.

**Pull request merged**
