### PR TITLE
Update maven.yml

### PR DESCRIPTION
**Pull request by laeubi**
Cache by base ref

### CODE REVIEW

**Comment by akurtakov** [comment]
As my GH actions-fu is not that good - what is gained that way? Don't hesitate to put the reply in the git commit too for further reference. Note that GH is still new for eclipse community so every bit of knowledge matters.

**Comment by laeubi** [comment]
This is that each branch get its own cache, nothing one needs to care about most of the time, but as the m2 cache of Tycho 2.6.x is incompatible with Tycho 2.7.x+ (what is used internally when building 2.7.x) I try to separate these two caches.

**Comment by laeubi** [comment]
by the way this should actually not be necessary so this is just an experiment...

**Comment by laeubi** [comment]
Obsolete

**Pull request closed without merging**
