### PR TITLE
Add test case for #271

### PR DESCRIPTION
**Pull request by apeteri**

### CODE REVIEW

**Comment by laeubi** [comment]
@apeteri thanks for this testcase, @mickaelistria do you have an idea why it is necessary to download the artifacts.xml as part of the build? Could this be related to the "lazy download" you have added a while ago? Maybe a workaround would be to always download artifacts+content xmls together...

**Comment by mickaelistria** [comment]
> do you have an idea why it is necessary to download the artifacts.xml as part of the build?

I believe publish-product goal adds the product *and all its dependencies* into the repository. So since dependencies have to be downloaded at that stage (and weren't necessary earlier), the artifacts.xml is queried at that stage.
However, I don't know about the `mvn` protocol and why it would miss some file if they're not fetched earlier. It seems like a bug in local expansion of the `mvn:` based p2 repo.

**Comment by laeubi** [comment]
I have replaced the maven site with a `file` reference by extracting it and then everything works. My guess is that if it is  downloaded before it is cached and the `publish-product` uses that cached location, while here it needs to fetch it initially and fails (maybe because `mvn` protocol is not known at that place).

**Comment by laeubi** [comment]
@apeteri I have simplified the product a bit according to my test only a very minimal configuration is required to reproduce the issue

**Comment by laeubi** [comment]
@apeteri the automatic rebase failed here can you please rebase manually?

**Comment by apeteri** [comment]
The ECA check is complaining about @laeubi's e-mail address, not sure why 😕. My agreement looks to be still in effect.

**Comment by laeubi** [comment]
Yeah don't mind that, I just want to see if with the rebase the build works fine :-)

**Comment by laeubi** [comment]
Thanks for the test-case :-)

**Pull request merged**
