### PR TITLE
[#1127] reproducer for addJars issue

### PR DESCRIPTION
**Pull request by cdietrich**
[#1127] reproducer for addJars issue

### CODE REVIEW

**Comment by cdietrich** [comment]
@laeubi is this enhough for a reproducer?

**Comment by laeubi** [comment]
Yes this looks good

**Comment by laeubi** [comment]
I'll mark this as draft until I can take a more detailed look here...

**Comment by laeubi** [comment]
Included in https://github.com/eclipse/tycho/pull/1177

**Pull request closed without merging**
