### PR TITLE
Replace StringBuilder by StringJoiner where suitable

### PR DESCRIPTION
**Pull request by HannesWell**
With this PR I suggest to replace StringBuilder by StringJoiner (or associated methods)  where elements are joined together and StringBuilder is not the ideal solution.

### CODE REVIEW

**Review by Bananeweizen — APPROVED** [review]
Did you use some static code analysis tool to find these or was that purely manual inspection? I'm always eager to add more static code analysis to my tool set, too. :)

**Comment by mickaelistria** [comment]
Apparently, on of this changes causes a regression in tycho-compiler-plugin.

**Comment by laeubi** [comment]
@HannesWell just to verify everything works as expected: Did you get a mail notification from github about the failing workflow?

**Comment by laeubi** [comment]
> Apparently, on of this changes causes a regression in tycho-compiler-plugin.

You should then add a negative review to this to block the ability to merge this change.

**Comment by mickaelistria** [comment]
> You should then add a negative review to this to block the ability to merge this change.

The 2 automated builds already did it.

**Comment by HannesWell** [comment]
> 
> Apparently, on of this changes causes a regression in tycho-compiler-plugin.

I will have a look at it,

> 
> @HannesWell just to verify everything works as expected: Did you get a mail notification from github about the failing workflow?

Yes I did. 

> 
> Did you use some static code analysis tool to find these or was that purely manual inspection? I'm always eager to add more static code analysis to my tool set, too. :)

Unfortunately the static analyser I use (Sonar Lint) did not mark this, but I used the call hierarchy of `StringBuilder.length()` respectively `AbstractStringBuilder.length()` to find all usages in tychos code base and most of them could be replaced by a StringJoiner. So at least the search was not purely manual.

**Comment by HannesWell** [comment]
The second commit seems to have fixed the issue.
The remaining build failure happens also on the master branch:
```
[ERROR] Tests run: 3, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 576.236 s <<< FAILURE! - in org.eclipse.tycho.test.p2Repository.MavenP2SiteTest
[ERROR] testPGP(org.eclipse.tycho.test.p2Repository.MavenP2SiteTest)  Time elapsed: 533.06 s  <<< ERROR!
```

Maybe also this stack-trace is of interest:

```
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-p2-repository-plugin:2.5.0-SNAPSHOT:assemble-maven-repository (maven-p2-site) on project pgp-site: Fetching  PGP key failed: java.io.IOException: retry count exceeded -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.eclipse.tycho:tycho-p2-repository-plugin:2.5.0-SNAPSHOT:assemble-maven-repository (maven-p2-site) on project pgp-site: Fetching  PGP key failed: java.io.IOException: retry count exceeded
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: org.apache.maven.plugin.MojoExecutionException: Fetching  PGP key failed: java.io.IOException: retry count exceeded
    at org.eclipse.tycho.plugins.p2.repository.MavenP2SiteMojo.loadPublicKey (MavenP2SiteMojo.java:404)
    at org.eclipse.tycho.plugins.p2.repository.MavenP2SiteMojo.execute (MavenP2SiteMojo.java:309)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: java.io.IOException: retry count exceeded
    at org.eclipse.tycho.plugins.p2.repository.MavenP2SiteMojo.openStream (MavenP2SiteMojo.java:440)
    at org.eclipse.tycho.plugins.p2.repository.MavenP2SiteMojo.loadPublicKey (MavenP2SiteMojo.java:391)
    at org.eclipse.tycho.plugins.p2.repository.MavenP2SiteMojo.execute (MavenP2SiteMojo.java:309)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
```

**Comment by mickaelistria** [comment]
Thanks @HannesWell , such code improvements are really welcome!

**Comment by laeubi** [comment]
> The remaining build failure happens also on the master branch

Feel free to add an `@Ignore` to this test if it keeps failing, I have seen similar failures in the past for some other test that fails when the network is slow.

**Comment by HannesWell** [comment]
> 
> Thanks @HannesWell , such code improvements are really welcome!

Thanks, that good to know.

> 
> 
> > The remaining build failure happens also on the master branch
> 
> Feel free to add an `@Ignore` to this test if it keeps failing, I have seen similar failures in the past for some other test that fails when the network is slow.

I don't know the details of the test, but wouldn't it be better if the test does not depend on a network connection?

**Comment by laeubi** [comment]
There are some "offline" integration tests, all other integration test generally require a working internet-connection.

**Comment by HannesWell** [comment]
For those who are interested:
Eclipse Clean-ups provide in the "Java-Feature" tab save Action called "Use String.join() when possible".
Maybe this would have catched some cases her (but probably not all).

**Pull request merged**
