### PR TITLE
Update Jenkinsfile

### PR DESCRIPTION
**Pull request by laeubi**
Exclude MD files and github workflow changes from triggering a build

### CODE REVIEW

**Comment by akurtakov** [comment]
Is this one still planned/needed?

**Comment by laeubi** [comment]
Actually it would be useful but it seems I have to find out the correct syntax for this. The idea is that we do *not* trigger a CI build if the github actions changes or if only documentation is changed as this is wasted time then...

**Comment by akurtakov** [comment]
This one conflicts already. Should we keep it?

**Comment by laeubi** [comment]
I'll close this for now, seems there is not much interest...

**Pull request closed without merging**
