### PR TITLE
Remove deprecated packaging types

### PR DESCRIPTION
**Pull request by mickaelistria**

### CODE REVIEW

**Comment by laeubi** [comment]
@mickaelistria do you still plan to work on this? I think it might be good to rebase this as there are some changes that might make this more easier as I reduced the Localresolver usage already.

**Comment by mickaelistria** [comment]
I don't plan to work on it for a few weeks to be honest.

**Comment by mickaelistria** [comment]
I submitted this branch into Tycho project and created a new PR https://github.com/eclipse/tycho/pull/737, so other committers can participate in this effort if they're interested. Let's close this one.

**Pull request closed without merging**
