### PR TITLE
tycho-eclipserun-plugin: Integration test for bundle start level

### PR DESCRIPTION
**Pull request by sratz**

### CODE REVIEW

**Comment by sratz** [comment]
@mickaelistria Are these `src/it` tests actually executed during build?

**Comment by mickaelistria** [comment]
@sratz We usually have all itests together in the `tycho-its` module. I'd recommend you move your tests there as well to ensure a good integration.

**Comment by laeubi** [comment]
Yep no need for using tycho.extras/it anymore that's just for legacy reasons.

**Comment by mickaelistria** [comment]
Thanks, test looks good and runs well at. Let's merge.

**Comment by mickaelistria** [comment]
https://ci.eclipse.org/tycho/job/tycho-github/job/PR-889/3/testReport/org.eclipse.tycho.test.eclipserun/EclipseRunBundleStartLevelTest/

**Pull request merged**
