### PR TITLE
Improve handling / logging of baseline replacements

### PR DESCRIPTION
**Pull request by laeubi**
- use more dynamic default value
- remove the lock
- if baselines checks are enforced, error if no repository is defined
- give better log message in case of missing repositories

Fix https://github.com/eclipse/tycho/issues/943

### CODE REVIEW

**Comment by mickaelistria** [comment]
The commit doesn't fix the issue described in commit message, please rephrase commit message.

**Comment by laeubi** [comment]
> The commit doesn't fix the issue described in commit message, please rephrase commit message.

Why not? It fixes for me (hopefully) the issue I have described that there are strange errors and I have no clue whats wrong beside a not very informative message.

**Comment by mickaelistria** [comment]
See comment on bug message, you're looking at the wrong component and what you suggest here wouldn't fix anything. Please retitle to highlight it's some code or functional improvement, or abandon.

**Comment by laeubi** [comment]
I changed the title if you think its good for anything, my point is that I think I had not been guessing around if the messages are more clear ...

**Comment by mickaelistria** [comment]
>  if you think its good for anything

Yes, good commit messages matter to me (and many others) in several workflows and are a vital for project health when trying to lookup complex and old issues. A bad history makes it harder to resolve those.

> my point is that I think I had not been guessing around if the messages are more clear ...

Sure, and the new commit message is better at telling that; while the previous one was telling something totally different from what it's actually doing. So it's good now.

**Comment by laeubi** [comment]
@mickaelistria would you like to review the code? do you think this is still useful?

**Comment by mickaelistria** [comment]
>  do you think this is still useful?

The code or my review? ;)
I had a very quick look and I'm fine with the overall changes, so if you think it will help in the future, please merge.

**Comment by laeubi** [comment]
At least it causes no regression in the test suite :-D

**Comment by laeubi** [comment]
I'll postpone this as it seem that the actual issue is #947 and if no one else have demands here seem to only partially improve here.
e.g. BND has a https://github.com/bndtools/bnd/blob/master/maven/bnd-baseline-maven-plugin/README.md#full-reporting option to output additional details about the 'why' that would be useful here but as pointed out not (yes) possible due to the current structure (we might need to save some more details from previous stages in the project key-value-store for this).

**Pull request closed without merging**
