### PR TITLE
Issue #797 - add a custom transport based on URL#openStream() with caching of 404 responses

### PR DESCRIPTION
**Pull request by laeubi**
This is a draft on how Tycho could use a custom transport. This also is a showcase on how an alternate P2 transport might work, to investigate what is required and give a bigger picture for possible P2 enhancements.

### CODE REVIEW

**Comment by laeubi** [comment]
For measurement purpose i use the following simple project and add some statistics:
```
<?xml version="1.0" encoding="utf-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd"
    xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

    <modelVersion>4.0.0</modelVersion>
    <groupId>com.test</groupId>
    <artifactId>p2cache</artifactId>
    <version>1.0.0</version>
    <packaging>eclipse-plugin</packaging>

    <properties>
        <tycho.version>3.0.0-SNAPSHOT</tycho.version>
    </properties>

    <repositories>
        <repository>
            <id>eclipse</id>
            <layout>p2</layout>
            <url>https://download.eclipse.org/releases/2022-03/</url>
        </repository>
        <repository>
            <id>eclipse-link</id>
            <layout>p2</layout>
            <url>https://download.eclipse.org/rt/eclipselink/updates/</url>
        </repository>
    </repositories>
    
    <build>
        <plugins>
            <plugin>
                <groupId>org.eclipse.tycho</groupId>
                <artifactId>tycho-maven-plugin</artifactId>
                <version>${tycho.version}</version>
                <extensions>true</extensions>
            </plugin>
        </plugins>
    </build>
</project>
```

This results in: total 35 seconds for 104 requests where 56 not found response.

**Comment by laeubi** [comment]
The same with a simple etag based cache requires on a hot-cache only 7 seconds, this is mostly because poor caching performance see https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/1039

**Comment by mickaelistria** [comment]
Overall, I don't think we should add into Tycho a transport that's not maintained by p2. I see only pitfalls in maintaining multiple strategies for the same thing in different projects.
Would it be possible that you implement such a transport directly in p2 now?

**Comment by laeubi** [comment]
If we have a working example in tycho and there is conses in P2 team I probably could think about migrating the code to P2 but most likeley this will be a longer process as there is some strong demand to not change much in P2 at the moment...

**Comment by mickaelistria** [comment]
There is a consensus in the p2 team already that a solution without ECF is desired. There may be some demand to not change too much in p2 at once, but Tycho shouldn't be treated as p2's sandbox and p2 has to evolve. This transport can be an extra transport in p2, not opt-in by default (until we remove ECF) and Tycho could then be configured to pick one transport over the other.

**Comment by laeubi** [comment]
> There is a consensus in the p2 team already that a solution without ECF is desired

At least in the tickets I opened it was rather controversial to even change small things in that area...

> There may be some demand to not change too much in p2 at once

I think it won't work well without changing "too much" and I'm not sure if I can afford all the discussions and required changes (we would need to adjust in other areas also for sure as ECF is somehow referenced directly internally) without any immediate benefit. Especially we would need to add some "hooks" to support tycho what most likely will soon enter the discussion loop why P2 needs to change and if not tycho could simply implement it ...

Even if it could be solved in the 2022-06 release this is three month away and I'd like to benefit from it as soon as possible as 

1. it will greatly reduce build times
2. Will support true offline mode making current workarounds in tycho obsolete
3. Will allow defeat bad caching behaviors by a user configurable forced caching delay ( @jcompagner  has already asked for it long time ago)
4. I'm a bit tired of all these "please don't break user X that might relies on Y but we never know and are all concerned it ends in a big desaster" :-\

**Comment by laeubi** [comment]
This is now feature complete.

Final measurements for my example on second run to ensure caches are filled:

1. Standard P2 transport: 48 seconds
2. Tycho transport with disabled min-cache: 47 seconds
3. Tycho transport with 1hr min cache: 5 seconds

**Comment by laeubi** [comment]
@mickaelistria @akurtakov all checks are green, I would like to merge this after squashing/rebase so we can get feedback as soon as possible?

**Comment by mickaelistria** [comment]
Can you please create a new bundle from it with the necessary bits only, in order to increase change that this code one day gets moved to p2? In the current form, it seems like we add maintenance (and value) in Tycho without any positive effect on p2; while conceptually p2 is supposed to be the right place to fix things. So let's ensure we don't start building too much of this logic in a way that cannot then be backported to p2.

**Comment by laeubi** [comment]
> Can you please create a new bundle from it with the necessary bits only

This is not really suitable to be placed in a new bundle as it needs to interact with maven/tycho here.

> it seems like we add maintenance (and value) in Tycho without any positive effect on p2

As we do on many other places as well. The problem is that tycho requirements are often not p2 requirements...

> too much of this logic in a way that cannot then be backported to p2

It would be a lot of work to really integrate this in P2 as it is not just prting a few classes but would require to adjust P2 at just a few more places and as long as P2 wan't sto maintan strickt backward compatibility this is even more challenging without any gain (from tycho point of view...).

**Comment by mickaelistria** [comment]
OK, feel free to merge.

**Comment by mickaelistria** [comment]
Actually, before we merge it, can't we try removin https://github.com/eclipse/tycho/blob/b8183fd42099c701ce6fe0fe36e77e524fa3e899/tycho-bundles/tycho-bundles-external/tycho-bundles-external.product#L43..L49 at the same time?

**Comment by laeubi** [comment]
I'll try that, but PC directly references ecf on some places ...

**Comment by laeubi** [comment]
Hm... this won't work as we then need to remove ecf completely and there is no way for the user to choose ecf as an alternative way... So I think we would need to keep this for a while.

**Comment by mickaelistria** [comment]
OK.

**Pull request merged**
