### PR TITLE
Issue #711 create a p2-maven plugin

### PR DESCRIPTION
**Pull request by laeubi**
Signed-off-by: Christoph Läubrich <laeubi@laeubi-soft.de>

### CODE REVIEW

**Comment by laeubi** [comment]
@mickaelistria this already improves two things:

1. p2 (maven) dependencies are now managed in the `p2-maven-plugin` instead of the `tycho-build`
2. The P2 repository layout is defined in `p2-maven-plugin` instead of `tycho-core`

Further moves are all blocked by current p2 work (e.g. https://github.com/eclipse-equinox/p2/issues/20 ) and it becomes hard to keep this up-to date for a long time, so I'd like to merge this in the current state.

Probably it would be possible to move all the transport and custom tycho p2 stuff here as well, but this most probably would require more bundles using package imports, I'll try to investigate and open appropriate issues later on.

**Comment by mickaelistria** [comment]
That looks interesting. However, we cannot use the `org.eclipse.p2` namespace for packages. Tycho packages have to start with `org.eclipse.tycho` as per Eclipse Development Process specification.

**Comment by laeubi** [comment]
I could move it to whatever (just have to make sure it does not clash with any existing package) but we also have `org.eclipse.sisu` in tycho repo so probably there are a few exceptions from that rule?

**Comment by mickaelistria** [comment]
There are exceptions, or issues, some because of history (code moved between projects and there is an agreement to keep package name). But for new code, it's always best to have `org.eclipse.<project>` as package prefix.

**Comment by laeubi** [comment]
Maybe we can make an exception here if we kindly ask the p2 team to use the prefix `org.eclipse.p2.maven` (as this is not a bundle it should not be an issue anyways), because the idea is to have this only use p2-stuff separated from Tycho it seems odd to name it with something 'tycho' in it then... Probably we can even migrate the plugin to p2 but that seems to add a lot of inflexibility.... probably sometimes later when there is not much changes anymore?

**Comment by laeubi** [comment]
> p2 will never host Maven plugins

Why not? I think there is no technical reason as many projects offer a maven/grade/... plugin.

> f you want to start a new project for this code, feel free

Not sure if that's a bit oversized ... anyways I opened https://github.com/eclipse-equinox/p2/issues/23 as this would be a perquisite for any project depending on p2 not be delayed to much in case of changes.

**Review by mickaelistria — APPROVED** [review]

**Pull request merged**
