### PR TITLE
Revert "Remove tycho.mode=maven"

### PR DESCRIPTION
**Pull request by akurtakov**
Reverts eclipse/tycho#981

### CODE REVIEW

**Comment by thannerme** [comment]
Hi @akurtakov 

I switched from tycho 2.2.0 to 2.7.4. but somehow the tycho.mode=maven flag does not take effect any more. As far as I see in this PR, it should however again for 2.7.4?

**Comment by akurtakov** [comment]
It is not removed so should be working. Can you share reproducer for what is not working for you?

**Comment by thannerme** [comment]
a bit hard to reproduce in few lines. I execute following command, which now (using new tycho version now, command stayed the same) does the dependency analysis.. but I will check on my side also again then.

mvn -e -f pom.xml -B --no-transfer-progress -s /home/jenkins/workspace/xxxxx -Dstyle.color=always org.eclipse.tycho:tycho-versions-plugin:set-version -Pall -Dtycho.mode=maven -DnewVersion=xx -Dartifacts=root

**Comment by thannerme** [comment]
or is there another possibility to achieve skipping the dependency resolution? (cause you thought about removing the flag)

**Comment by thannerme** [comment]
@laeubi   Do you maybe have an idea or workaround? (I read https://github.com/eclipse-tycho/tycho/issues/676) 

in short: 
- i switched from tycho 2.2.0 to 2.7.4 
- use org.eclipse.tycho:tycho-versions-plugin:set-version  as only goal
- with Dtycho.mode=maven set

but with 2.7.4 now... dependency analysis is done nonetheless..

**Comment by laeubi** [comment]
I'm not aware of any workaround, `tycho.mode=maven` only skips the inital project resolving but don't take place at other places (e.g we are moving some work from that inital phase to the mojo phases) so it seems that `org.eclipse.tycho:tycho-versions-plugin:set-version` runs in a later phase that includes the resolving of project dependencies.

**Comment by thannerme** [comment]
ok. thx! but then this should not relate to migration from 2.2.0 to 2.7.4 I guess..

**Comment by laeubi** [comment]
`tycho.mode=maven` is nowhere documented, nor covered by any tests, so actually *anything* can happen between releases. If you think something is wrong the best way is provide an [integration-test](https://github.com/eclipse/tycho/wiki#providing-an-integration-test) to demonstrate the issue and then we can decide if/what can be done here.

**Comment by thannerme** [comment]
ok, thanks again. I will  do some more tests/ wait for tycho 3.0.0 and maybe come back to you then

**Comment by thannerme** [comment]
it seems to be related to the new available artifactID "tycho-build" in the extension.xml. 
I changed it when I saw the warning/info "org.eclipse.tycho.extras:tycho-pomless build extension will be replaced in a future version of Tycho by the new org.eclipse.tycho:tycho-build extension" in the logs.

I just changed it back.. and guess will stay with it as long as we use version < 3.x

**Comment by laeubi** [comment]
> it seems to be related to the new available artifactID "tycho-build" in the extension.xml.

Yes it is disabled there by intention.

**Comment by laeubi** [comment]
> I just changed it back.. and guess will stay with it as long as we use version < 3.x

Could you try out the current [tycho snapshot](https://github.com/eclipse/tycho/wiki#getting-tycho-snapshots) build and use the option  `-Dtycho.resolver.classic=false`?

**Comment by thannerme** [comment]
and using the artifactID tycho-build? this still does the dependency analysis

**Comment by laeubi** [comment]
> using the artifactID tycho-build and tycho-version set to 2.7.5-SNAPSHOT?

You need Tycho 3.0.0-SNAPSHOT for you tycho-maven-plugin, the tycho-build could be 2.7.5 or 3.0.0-SNAPSHOT (just take care about special instructions about using SNAPSHOTS in maven extensions).

Beside that, I think it would be good to provide an [integration-test](https://github.com/eclipse/tycho/wiki#providing-an-integration-test) to demonstrate the issue or a small reproducer project.

**Comment by laeubi** [comment]
@thannerme I have now [created a fix](https://github.com/eclipse-tycho/tycho/pull/1323) that detects if a dependency resolution is required or not for the requested Mojos of a project, so once the PR is merged, it should work for the `org.eclipse.tycho:tycho-versions-plugin:set-version` to use:

`mvn org.eclipse.tycho:tycho-versions-plugin:set-version -Dtycho.resolver.classic=false ... other arguments ....`

this will then still resolve direct dependencies between projects (but that should be really fast) but skip the expensive target platform resolution.

**Comment by thannerme** [comment]
Hi @laeubi 

thanks a lot! This seems to work  (I tested with 2.7.5 and artifactID tycho-build)

**Comment by laeubi** [comment]
Not that I'm aware of ... thats just standard maven behavior.

**Comment by thannerme** [comment]
I tried it by leaving it out and setting the plugin in the project's plugin configuration as described here (I thought that should also work)
https://ci.eclipse.org/tycho/job/tycho-sitedocs/lastSuccessfulBuild/artifact/target/staging/tycho-release/tycho-versions-plugin/plugin-info.html

**Comment by akurtakov** [comment]
Can further discussions/questions/etc be done separately to not hijack this PR history. https://github.com/eclipse-tycho/tycho/discussions is good place for it.

**Pull request merged**
