### PR TITLE
upgrade Tycho Surefire JUnit Jupiter 5.8 to 5.8.2

### PR DESCRIPTION
**Pull request by Bananeweizen**
Use Jupiter 5.8.2 instead of 5.8.1 at Tycho Surefire runtime, when
selecting the junit58 provider.

### CODE REVIEW

**Comment by laeubi** [comment]
@akurtakov is the license check covering this already or do we need to check this manually?

**Comment by akurtakov** [comment]
Yes, it's covered.

**Comment by mickaelistria** [comment]
> is the license check covering this already or do we need to check this manually?

I don't think the license check does cover artifacts other than plain "dependencies", here they're in maven-dependency-plugin configuration so they won't be considered.

**Comment by akurtakov** [comment]
When I said covered I was speaking for junit 5.8.2 and friends being already covered from IP side of things. I haven't looked at the mechanics here.

**Pull request merged**
